### PR TITLE
Add automatic build script for examples

### PR DESCRIPTION
**Pull request by leowzukw**
This script needs zsh

### CODE REVIEW

**Comment by dsheets** [comment]
`zsh` is a rare dependency. How about `sh`?

**Comment by leowzukw** [comment]
I could not make `sh` nor `bash` working properly, that is why I think `zsh` is better than nothing.

**Comment by samoht** [comment]
You are not the first one to report that. But there is already a way to build the examples:

```
./configure --enable-examples
make
```

But yes, this should be written in the README ...

**Comment by samoht** [comment]
Fixed by #127

**Comment by leowzukw** [comment]
Great

**Pull request closed without merging**
