### PR TITLE
irmin.type: add empty generic for an uninhabited type

### PR DESCRIPTION
**Pull request by CraigFe**
This resolves https://github.com/mirage/irmin/issues/957.

There is no canonical empty type in the OCaml stdlib, so here I define one of our own. There are no tests as the `empty` generic is hard to interact with by design. A solution to https://github.com/mirage/irmin/issues/958 would permit at least one test in terms of `Irmin.Type.pp_ty`.

### CODE REVIEW

**Comment by CraigFe** [comment]
Rebased.

**Comment by CraigFe** [comment]
Travis reminds me that the empty variant is only supported by OCaml `>= 4.07`, so this can wait until we drop support for `4.06`.

**Comment by samoht** [comment]
I don't think we have 4.06 users anymore. Moreover, the unofficial contract for MirageOS project is to support only the last two versions of the OCaml compiler -- as 4.09 is the most recent version, I'm favour of dropping support for that compiler version.

**Comment by avsm** [comment]
I am definitely in favour of choosing cleaner code over backwards compatibility with OCaml 4.06 here.

**Comment by hannesm** [comment]
FWIW, I use lower bounds on 4.07.0+ as well (in dns, mirage-crypto, ..), the reasons being: more issues (segmentation faults) are fixed in the OCaml runtime; and much better exhaustiveness checking of pattern matches / GADT qualifications. It also does not need stdlib-shims etc.

I'm actually looking forward to use 4.08.0 as lower bound, which has lots of nice Stdlib improvements (introduction of Result, Option, ..).

**Comment by CraigFe** [comment]
In that case, I'll drop support for `4.06` along with this PR.

@pascutto: this can now be reconsidered for merge.

**Pull request merged**
