### PR TITLE
Prepare 2.6.0 release

### PR DESCRIPTION
**Pull request by CraigFe**
2.6.0 contains the bugfixes currently in `master` + the upgrade to Git.3.4.0.

### CODE REVIEW

**Comment by samoht** [comment]
Which branch does it come from? 2.5 ?

**Comment by CraigFe** [comment]
Yes, 2 is currently set to 2.5.

**Comment by samoht** [comment]
LGTM

**Comment by CraigFe** [comment]
Corresponding opam-repository PR: https://github.com/ocaml/opam-repository/pull/18598.

**Comment by CraigFe** [comment]
Now merged upstream. I'll adjust the `master` changelog accordingly.

**Pull request merged**
