### PR TITLE
use year instead of license per year

### PR DESCRIPTION
**Pull request by AntouanK**
the year was saved as a "license"

### CODE REVIEW

**Comment by pascutto** [comment]
Thank you for catching this!
Could you please run `dune build @fmt --auto-promote` to fix the formatting and make the CI happy?

**Comment by AntouanK** [comment]
Done :) 

Also, can I ask for a bit more on the graphql example?
Maybe how we branch/merge?

I'm trying irmin out because we want to use it in our company project, and I'm not that familiar with OCaml so it's a slow process for me to figure it out.

Thank you.

**Comment by pascutto** [comment]
Thank you :+1: 
Did you have a look at [this blog post](https://tarides.com/blog/2019-11-27-introducing-the-graphql-api-for-irmin-2-0)? It contains more examples (including branches and merges) that might help you.

**Comment by pascutto** [comment]
GraphQL's `Int` values are signed 32 bits integers, so you would need to keep `year` as an `int32` to comply to that.
Was there a specific reason for changing it?

**Comment by AntouanK** [comment]
> GraphQL's `Int` values are signed 32 bits integers, so you would need to keep `year` as an `int32` to comply to that.
> Was there a specific reason for changing it?

I just couldn't make it compile otherwise. Like I said, I have very little understanding of ocaml.
I'll add a commit and see if it's correct.

**Comment by AntouanK** [comment]
> Thank you +1
> Did you have a look at [this blog post](https://tarides.com/blog/2019-11-27-introducing-the-graphql-api-for-irmin-2-0)? It contains more examples (including branches and merges) that might help you.

Will take a look now.
Thank you!

**Comment by AntouanK** [comment]
> > Thank you +1
> > Did you have a look at [this blog post](https://tarides.com/blog/2019-11-27-introducing-the-graphql-api-for-irmin-2-0)? It contains more examples (including branches and merges) that might help you.
> 
> Will take a look now.
> Thank you!

I think that guide is outdated, or my copy of irmin has a problem, because I cannot reproduce the first query the guide shows :( 

Screenshot_2020-11-09_13-22-00

**Comment by CraigFe** [comment]
CI looks happy – modulo an existing issue with configuration – so merging; thanks for the fix!

**Pull request merged**
