### PR TITLE
irmin-pack: improve test suite coverage of Conf values

### PR DESCRIPTION
**Pull request by CraigFe**
Changes the `irmin-pack` test suite instantiation to test multiple choices for the following configuration options:

- ``indexing_strategy = always | minimal`` (as before)
- ``entries = 2 | 32``
- ``stable_hash = 3 | 256``
- ``contents_length_header = None | Some `Varint``
- ``inode_child_order = `Hash_bits | `Seeded``

This should provide better coverage overall.

### CODE REVIEW

**Comment by Ngoguey42** [comment]
I think we should test for `stable_hash = 0` instead of `3`

See my comment here https://gitlab.com/tezos/tezos/-/merge_requests/4145#note_822417514

**Comment by CraigFe** [comment]
Small issue with that one :sweat_smile:

```
> [FAIL]        PACK { index = always }          13   High-level store merges.

  ... with 59 subsequent tests skipped.

┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        PACK { index = always }          13   High-level store merges.                     │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

...

[exception] Irmin_pack__Inode.Make_internal(Conf)(H)(Key)(Node).Raw.Invalid_depth(1, 0, _)
            Raised at Irmin_pack__Inode.Make.check_depth_opt in file "src/irmin-pack/inode.ml", line 2099, characters 36-78
            Called from Irmin_pack__Inode.Make.find.(fun).find in file "src/irmin-pack/inode.ml", line 2107, characters 10-43
            Called from Irmin_pack__Inode.Make_internal.Val_portable.of_raw.find in file "src/irmin-pack/inode.ml", line 1902, characters 37-62
            Called from Irmin_pack__Inode.Make_internal.Val_impl.Ptr.target.(fun) in file "src/irmin-pack/inode.ml", line 717, characters 22-46
            Called from Irmin_pack__Inode.Make_internal.Val_impl.find_value.aux in file "src/irmin-pack/inode.ml", line 1251, characters 18-108
            Called from Irmin__Tree.Make.Node.findv_aux.of_value in file "src/irmin/tree.ml", line 968, characters 14-43
...
```

Let's fix it and then use that :+1:

**Comment by Ngoguey42** [comment]
Should we merge this one in the meantime?

**Comment by CraigFe** [comment]
> Should we merge this one in the meantime?

I think we might as well. I've made https://github.com/mirage/irmin/pull/1738 as a follow-up issue; will take a look at that now.

**Review by Ngoguey42 — APPROVED** [review]

**Pull request merged**
