### PR TITLE
Sync merge example and doc example

### PR DESCRIPTION
**Pull request by shonfeder**
Hi! I was trying out Irmin for the first time, and following the example on in the `irmin.mli` docs, but found that some of the code didn't compile.

The principle point of this PR is to sync the docs with the current code in `examples/custom_merge.ml` (12fac5f). Along the way I also

- fixed one misnamed target (i think) that blocked (abe3758)
- made some tiny tweaks to the example code, for readability and documentation (cf794de)
  - this commit also applies auto formatting my editor imposed due to the `.ocamlformat` config in the repo. Let me know if you'd like me to revert that stuff.

### CODE REVIEW

**Comment by CraigFe** [comment]
Hi @shonfeder. Thanks for the fixes!

LGTM. Whatever formatting is applied here doesn't seem to match the `.ocamlformat` config in the repository, and so our CI won't accept it. Could you reformat with `dune build @fmt` and see if that fixes it?

(Hopefully we can get `mdx` to do this sort of syncing in future...)

**Comment by shonfeder** [comment]
Oh indeed! It looks like my emacs environment was using an incorrect ocamlformat config for some reason.  I've updated the formatting, hopefully this is the correct format now :)

Using `mdx` here will be great. `mdx` in generally is great :D

**Comment by shonfeder** [comment]
Hmm, fmt still failing, and unfortunately ocamlformat is crashing too! 

```
$ opam exec -- dune build @fmt
 ocamlformat src/irmin/.formatted/irmin.mli (exit 1)
(cd _build/default && /home/sf/Sync/oss/irmin/_opam/bin/ocamlformat --intf src/irmin/irmin.mli) > _build/default/src/irmin/.formatted/irmin.mli
ocamlformat: Cannot process "src/irmin/irmin.mli".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: formatting did not stabilize after 10 iterations.
```

I haven't been able to get ocalmformat to show any illuinating info about why it's failing unfortunately. I'll keep digging around tho.

**Comment by CraigFe** [comment]
From a quick look with the `--debug` flag, it looks like OCamlformat is getting stuck in a cycle of not being sure where to place the `(* Persist a new entry in the log *)` comment.

Changing that comment to be a doc-comment seems like a nice workaround, but we should still report it upstream.

**Comment by shonfeder** [comment]
Ah! Thanks for helping point that out. This seems to be a case of https://github.com/ocaml-ppx/ocamlformat/issues/1449

**Review by CraigFe — APPROVED** [review]
Thanks a lot!

**Comment by shonfeder** [comment]
Thank *you*, @CraigFe!

**Pull request merged**
