### PR TITLE
First tentative for Ir_funview.

### PR DESCRIPTION
**Pull request by OCamlPro-Henry**
This extract some part of Ir_view into a new submodule Ir_funview. This new module exports a functional interface for views.

This is a tentative implementation of "functional view". This is a quick hack that I still need to proof-read myself, but this early PR is here for feedbacks. Is this of any interest except for me ?

This code is used in a soon-to-be-open-sourced project, where locally we need to backtrack the store. In this "semi-intensive" process, commiting-to-disk would be too expansive.

### CODE REVIEW

**Comment by OCamlPro-Henry** [comment]
See #109.

**Comment by samoht** [comment]
Thanks Gregoire!

/cc @talex5 

We discussed a lot about that feature and I think the initial mutable views model was maybe not the best design choice ever :p I'll try to review the patches soon.

**Comment by talex5** [comment]
There's also: https://github.com/docker/datakit/blob/master/src/ivfs/ivfs_tree.mli

It's not quite an immutable view (doesn't record and replay actions), but it does cover many uses of them.

**Comment by samoht** [comment]
@talex5 and @OCamlPro-Henry I am working on revamping the Irmin API to be closer to what both of you have in mind. This will remove the current mutable views and use the implementation provided in that patch as the default mechanism to express Irmin views. I'll keep you informed on the progress, but I expect to release that in the next couple of weeks (and I'll bump the API to 1.0).

**Comment by samoht** [comment]
Closing the PR as this has been incorporated into #397

**Pull request closed without merging**
