### PR TITLE
irmin-pack

### PR DESCRIPTION
**Pull request by samoht**
/cc @dinosaure and @Julow

### CODE REVIEW

**Comment by samoht** [comment]
This is now passing all the tests (at least locally, let's see what the CI is saying).

I still need to benchmark how much space we gain vs. other backends and have a better ideas of the runtime costs.

**Comment by samoht** [comment]
I've rebased this against master.

**Comment by samoht** [comment]
What is needed before merging:
- [ ] atomic update of offsets -- probably using a separate file + atomic rename
- [ ] add a proper file header to distinguish between the various file kinds
- [ ] improve the way the dictionary is loaded by reading pages
- [ ] a few more benchmarks

**Comment by samoht** [comment]
Early results, on the Tezos codebase.

```
$ ./tezos-node snapshot import mainnet-2019-04-05.full --reconstruct

**Comment by avsm** [comment]
Wow, that's close to an order of magnitude improvement from current Tezos.

**Comment by samoht** [comment]
This is ready to merge. We'll do minor adjustment in subsequent pull requests.

**Comment by avsm** [comment]
Congratulations on getting this merged!  What were the final improvements on the Tezos codebase?

**Comment by samoht** [comment]
This allows to compress Tezos database by a factor ~10 (e.g. 440k levels now uses 15G of disk size), with an import speed equivalent to the current lmdb. We are still working on making this faster, with a better control of the memory consumption (which is still a bit too high to my taste). 

I think we are in good track to propose this alternative backend to Tezos more officially, hopefully in a couple of weeks max. and gather a larger feedback from tezos users.

**Pull request merged**
