### PR TITLE
irmin: better signature for Tree.length

### LINKED ISSUE #1666: Add Node.length
It's useful to have this exposed as the node implementations can do this more efficiently than folding over all the keys. Inodes store this directly in the object binary format, so it's a cheap.

The use-case for this is to store a list as an (index -> entry) reverse dictionary. With that scheme, to insert a new entry you need to get the size of the existing list efficiently first.

### PR DESCRIPTION
**Pull request by samoht**
Fix #1666

### CODE REVIEW

**Comment by maiste** [comment]
LGTM :+1:

**Review by maiste — APPROVED** [review]

**Comment by CraigFe** [comment]
I'm not sure I understand why this is a better signature than the one before: it seems good to be explicit that "length" is a property of nodes and not contents values (if possible), and one can get the node out of a tree by `destruct`-ing it. Can you fill me in on how this impacts TORU proofs?

**Comment by samoht** [comment]
> I'm not sure I understand why this is a better signature than the one before:

That's the only function using a `node` as a parameter and it's a bit odd that it's not symmetric with `List.length (list t)`.

TORU want to encode a list of values as a reverse dictionary `index * value`: e.g. the list ["foo"; "bar"] could be encoded into:
```
/data/0 = "foo"
/data/1 = "bar"
``
With this scheme, adding a new entry "toto" is doing `let n = Tree.length t in add "/data/$n" "toto"` and thus `length` has to be efficient (and not scan the full node).

**Comment by CraigFe** [comment]
> Edit: Actually by writing that pseudo-code I realise that we probably want `val length: t -> path -> int` to be closer to the signature of `val list ...`

Passing the path would indeed make it more consistent, in which case LGTM. Thanks for the explanation :-)

**Comment by samoht** [comment]
Updated with the new API.

**Pull request merged**
