### PR TITLE
Refactor pack

### PR DESCRIPTION
**Pull request by icristescu**
This PR prepares irmin-pack for PR #882 (it contains its first 5 commits). 

Most importantly, this PR extracts the common parts from irmin-pack -- reused by  [irmin_pack_layers](https://github.com/mirage/irmin/pull/882/commits/a14758a152c4810cc35d7b47a6ed586795235bfc#diff-52ce06d08638434eac31d8f0240b3b5e) and inode -- reused by [inode_layers](https://github.com/mirage/irmin/pull/882/commits/a14758a152c4810cc35d7b47a6ed586795235bfc#diff-08739a17a18db6e6c3de271700745c38R41-R53). 

It's not great, in particular I don't have an `.mli` for `inode_common.ml` because I wanted to avoid writing a lot of module signatures. So any suggestions to ameliorate this are very welcome :)

### CODE REVIEW

**Comment by CraigFe** [comment]
Thanks :slightly_smiling_face: Here's some initial thoughts, and I'll spend some more time thinking about this tomorrow. 

I'm not a big fan of having large `Common` modules, since it suggests to me that we don't really know where this code belongs. I've made some initial code-review suggestions in https://github.com/icristescu/irmin/pull/5, which mostly splits the code that's now in `common.ml` to `config.ml` and `store.ml`.

The lack of an interface for `Inode_common` feels like a problem, and combined with it's name again suggests to me that it's not a well-understood abstraction boundary in the code. Perhaps we can find a better way to wrap this code in an API that makes sense for it; if that leads to us being able to test it directly, that would be great. (Bearing in mind that at some point we have to write a spec for what this does...)

**Comment by icristescu** [comment]
I removed the `inode_common` file, and kept only the inode files.
I split the Make functor of inodes into three functors, roughly 
- `Make_intermediate` contains everything before calling `Pack.Make`
- `Make_ext`contains everything after the call to `Pack.Make`, i.e it takes a inode (obtained by `Pack.Make`) and creates the inode store
- `Make` calls `Make_ext` with the inode obtained from `Make_intermediate`.
I'm doing this because the layered store wraps a pack into a layered pack, that is then forwarded to the inode functor. The pack and layered pack have disjoint signatures.
The layered store is now rebased over this PR, if you want to check how this plays with inode_layers it's in [this commit](https://github.com/mirage/irmin/pull/882/commits/2f29deb6cedd0839c05988c671e88d89ab6b0c00).

**Review by CraigFe — APPROVED** [review]
Very clean; thanks!

**Comment by icristescu** [comment]
The Travis CI job on `irmin-mirage-git` is consistently failing, but it is on master too, so I'm merging this.

**Pull request merged**
