### PR TITLE
irmin.type: test the generic `to_string` operation

### PR DESCRIPTION
**Pull request by CraigFe**
This adds an initial batch of tests for the generic serialisation function.

I also took the opportunity to add `ppx_irmin` as a test-dependency, and used it to make the test code a bit more concise.

These tests expose several behaviours that I consider either unintuitive or buggy, mostly caused by the operation deferring to `pp_json` for complex types:

- `()` stringifies to `""` (the empty string) when called directly with `Irmin.Type.(to_string unit)`, but to `null` when found inside a composite type.
- In the same manner, `true` stringifies to `"true"` or `1` respectively (and similarly for `false`).
- `option` types serialise to `null` in the `None` case and have no tag in the `Some` case (leaking from the JSON encoding). This has some problems, for instance causing `unit option` types to be serialised as `null` in both `Some ()` and `None` cases.

### CODE REVIEW

**Comment by CraigFe** [comment]
Rebased.

**Comment by samoht** [comment]
LGTM

**Comment by CraigFe** [comment]
Will wait to merge https://github.com/mirage/irmin/pull/967 first, since some of these tests will change as a result of that.

**Comment by CraigFe** [comment]
Now rebased over https://github.com/mirage/irmin/pull/967.

**Pull request merged**
