### PR TITLE
ppx_irmin: strengthen the tests to compile and run the output

### PR DESCRIPTION
**Pull request by CraigFe**
... and use this to catch a bug in the `passing/nonrec.ml` test.

Also adds a (broken) test case witnessing the bug described by https://github.com/mirage/irmin/issues/923 (cc. @pascutto). I couldn't find an easy way to assert that this bug exists as part of `dune runtest` (doing so would likely require something like [janestreet/toplevel_expect_test](https://github.com/janestreet/toplevel_expect_test)).

### CODE REVIEW

**Comment by CraigFe** [comment]
Unfortunately, it seems the workflow proposed here isn't supported by OCaml-CI.

We'd like to be able to test `ppx_irmin` by compiling the resulting code against the `irmin` API. Neither depends on the other, but they have cyclic test dependencies:
 - `irmin` → `ppx_irmin` (`with-test`), though at some point this may be a true dependency
 - `ppx_irmin` → `irmin` (`with-test`)

TravisCI doesn't have the same problem since it handles each package independently.

**Comment by samoht** [comment]
```
irmin → ppx_irmin (with-test)
```
Maybe we should not depend on `ppx_irmin` in irmn's tests then, and just commit the generated code.

**Comment by CraigFe** [comment]
> Maybe we should not depend on `ppx_irmin` in irmn's tests then, and just commit the generated code.

I'd rather not go with that as a solution here, since it becomes another reason not to use `ppx_irmin` in `irmin` itself.

If @talex5 thinks the issue can be fixed CI-side, let's do that instead.

**Comment by CraigFe** [comment]
As pointed out by @talex5, this is now unblocked with the new solver branch of the CI (currently deployed).

I'll rebase tomorrow, then we should wait until https://github.com/ocurrent/ocaml-ci/pull/167 is merged before merging here.

**Comment by CraigFe** [comment]
CI failure in `irmin-http` unrelated. Merging.

**Pull request merged**
