### PR TITLE
irmin-layers: run all the tests for irmin-pack.layers

### PR DESCRIPTION
**Pull request by samoht**
On top of #1421 and #1422 to make the tests pass

### CODE REVIEW

**Comment by samoht** [comment]
@zshipko if you have time, could you review that PR?

**Review by zshipko — COMMENTED** [review]
I think this looks good - I happened to be looking at this code yesterday after noticing that `batch` is part of the commit bottleneck in the tezos benchmarks, accounting for ~95% of the time spent making a commit. It definitely seems like reducing the number of locks would make debugging easier.

From looking at a few runs it doesn't look like this has any effect on commit times but I will make some graphs to compare more easily.

**Comment by zshipko** [comment]
`self_contained` is the current branch I'm using for tezos benchmarking and `self_contained+irmin-layers-test` is that branch rebased on top of this PR. 

self_contained
self_contained+irmin-layers-test

It looks like this PR doesn't change the issue I'm seeing with long commits - since at least it doesn't have any major negative effects, I would say this is safe to merge.

**Comment by CraigFe** [comment]
Closing as the layered store is currently disabled.

**Pull request closed without merging**
