### PR TITLE
Prepare 2.7.2 release 

### PR DESCRIPTION
**Pull request by icristescu**

### CODE REVIEW

**Comment by CraigFe** [comment]
Looks good overall. This adds a `vendors/tezos-context-hash` submodule that I believe we don't need in 2.7.

For the future, when cherry-picking to these backport branches it can be a good idea to use `-x` to add some context about where the commit came from – not worth worrying about now.

**Comment by icristescu** [comment]
> For the future, when cherry-picking to these backport branches it can be a good idea to use `-x` to add some context about where the commit came from – not worth worrying about now.

Noticed those only after opening the PR, I added them too. 

Because of the progress library, I think we need to also upgrade the index version (which I did [here](https://github.com/mirage/irmin/pull/1490/commits/a98db74a8307693c94da3ea1efd9a3d63ef513a6)) let me know if I got this wrong.

**Comment by CraigFe** [comment]
> I think we need to also upgrade the index version (which I did here) let me know if I got this wrong.

This looks fine :+1: Requiring 1.4.1 over 1.4.0 seems like a good idea anyway -- we'll just need to add the latest version of `progress` to the Tezos opam-repository when we make the upgrade.

**Review by CraigFe — APPROVED** [review]

**Comment by CraigFe** [comment]
Thanks! Now released here: https://github.com/ocaml/opam-repository/pull/19088

The `master` changelog will need updating accordingly.

**Pull request merged**
