### PR TITLE
Finer-grained LRU purge

### PR DESCRIPTION
**Pull request by samoht**
Try to selectively remove entries from the LRU that are not in the mapping file. That doesn't seem to pass the tests for a reason that I don't understand yet (`c1` seems to be present in the prefix!)

### CODE REVIEW

**Comment by samoht** [comment]
I've pushed a fix, but I'm not super happy about it: it seems that the prefix contains more data than it should. I'm not sure to understand why.

**Comment by samoht** [comment]
@zshipko I think I'm ok with the changes now - could you check that the benchmarks stats are improved with this?

**Comment by zshipko** [comment]
Here are some stats comparing 3.1.1, https://github.com/mirage/irmin/pull/1998 and this PR: 
[lru-stats.txt](https://github.com/mirage/irmin/files/9154860/lru-stats.txt)

From looking at that it seems like fixing the LRU bug has the most effect and these additional changes might provide marginal improvements in some areas but also uses a bit more memory.

**Comment by samoht** [comment]
The more straightforward #1998 was prefered over this PR.

**Pull request closed without merging**
