### PR TITLE
Import irmin-graphql

### PR DESCRIPTION
**Pull request by zshipko**
This PR merges the existing `irmin-graphql` code into our repository with very few changes.

Additionally, it adds a `graphql` command to start a GraphQL server from the CLI.

### CODE REVIEW

**Comment by samoht** [comment]
It seems that the CI scripts need some update:

```
#=== ERROR while compiling irmin-unix.dev =====================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(file:///home/travis/build/mirage/irmin)
# path        ~/.opam/4.06.1/.opam-switch/build/irmin-unix.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p irmin-unix -j 1
# exit-code   1
# env-file    ~/.opam/log/irmin-unix-9632-ffb3fd.env
# output-file ~/.opam/log/irmin-unix-9632-ffb3fd.out
### output ###
# File "src/irmin-unix/dune", line 4, characters 69-82:
# 4 |  (libraries   irmin irmin-fs irmin-git irmin-http git-unix irmin-mem irmin-graphql
#                                                                          ^^^^^^^^^^^^^
# Error: Library "irmin-graphql" not found.
# Hint: try: dune external-lib-deps --missing -p irmin-unix @@default
```

Maybe a missing entry in the `PINS` variable?

**Comment by zshipko** [comment]
Okay, should be fixed now (it seems like the appveyor issue is unrelated). There were some weird dependency issues that I had overlooked when pulling the code in.

**Comment by samoht** [comment]
Could you rebase it on master? Thanks

**Comment by zshipko** [comment]
Sure, just rebased it

**Comment by zshipko** [comment]
Let me know if any other changes are required in order for this to be merged!

**Comment by samoht** [comment]
LGTM, thanks! Excited to see a first-class GraphQL API in Irmin!

**Comment by zshipko** [comment]
Agreed, this will be a very nice addition! @andreas has also been working on a `graphql-cohttp` package which we will be able to use for Mirage support!

**Pull request merged**
