### PR TITLE
fix translation between Git commit message and Irmin info

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
@dinosaure any opinion on how we should create commit messages? Not sure what is the format with GPG message and if that's ok to have empty message and/or message which do not start by a newline.

**Comment by hannesm** [comment]
@cfcs may know what GPG-signing in git involves, and is developing OpenPGP in OCaml https://github.com/cfcs/ocaml-openpgp

**Comment by cfcs** [comment]
As far as I understand, gpg-signing commits entails appending a whole ascii-armored `----- BEGIN PGP SIGNATURE -----`-blob onto the end of the commit. I have a small utility in the works that can be used with c-`git` to check repositories, but it relies on maintaining an external configuration per-repository listing which keys are allowed to commit, and it works poorly if you merge commits from people external to the set of maintainers.

`man git-config` -> `gpg.program` has some more details, as does the manpages for `git-verify-tag`; `git-verify-commit`; `git-tag` (look for `--sign` or `-s`);  `git-commit` (`--gpg-sign` or `-S`).

The c-`git` interface for validating these signatures is pretty useless, notably you verify that *someone* in your keychain signed the commit, but it doesn't try to match the signature with the author or committer. This is probably so because `rebase` and other operations (like merging pull-requests from people who shouldn't be "authors" with the PGP-level privileges to modify the repository).

This kind of distinction between "levels of trust" is something OpenPGP is notoriously bad at, and it would frankly make more sense to use `x.509` here; you need a proper PKI that allows delegations of limited rights in order to design a proper solution, which is probably why `git` chose to do this half-solution compromise instead that doesn't really accomplish much.

A possible solution to the problem of "what if I want to merge someone's code without trusting them to publish to my master branch in the future" could perhaps be solved by having the repo maintainer sign a set of commits (like with a merge commit), from which you could then follow the SHA1/SHA256 chain, but that means you end up with a repository where *some operations* are safe/verified, and others (like checking out one of the intermediate commits as the head) become kind of complicated since you need to keep track of the trust root.

I think it *would* be possible to design a cryptographic solution to solve these problems, and I think it *would* be possible to design a sane API around it, but I find it hard to imagine that it would be compatible with the workflow people have come to expect from vanilla git, and in any case it would need more thinking/discussion/deliberation, I don't have a good solution on hand. In any case I would probably try to not make OpenPGP a component in this design.

Sorry to be a bit negative. :)

**Comment by samoht** [comment]
Thanks for the explanation! 

In your links, the GPG messages are indeed packed before the message (before the extra newline) and it seems that `ocaml-git` understand it correctly. So my fix is correct, but it also means that the signatures are lost during the git->irmin translation.

I will open a new issue to keep track of what needs to be added to either add first-class support for signed commits, or at least to have a way to delegate that to API clients.

**Pull request merged**
