### PR TITLE
irmin-pack: replace inode's Map by a list of pairs

### PR DESCRIPTION
**Pull request by samoht**
This needs to be tested more to understand the impact on more extensive benchmarks, but this seems to cut the memory usage of the tree benchmark by 40%.

### CODE REVIEW

**Comment by samoht** [comment]
On the tree benchmark (with a small trace):

before:
```
 | -- main metrics --       |
 | CPU time elapsed         |     0m25s
 | Wall time elapsed        |     0m25s
 | TZ-transactions per sec  |   373.190
 | TZ-operations per sec    |  4192.695
 | Context.set per sec      | 29609.231
 | tail latency (1)         |   0.682 s```

after:
```
 | -- main metrics --       |
 | CPU time elapsed         |     0m23s
 | Wall time elapsed        |     0m24s
 | TZ-transactions per sec  |   406.163
 | TZ-operations per sec    |  4563.142
 | Context.set per sec      | 32225.368
 | tail latency (1)         |   0.648 s
```

**Comment by metanivek** [comment]
@samoht no changes are showing up for this PR. Did you forget to push something? :smile:

**Comment by zshipko** [comment]
@metanivek I think another PR was based on this one and these changes have already been merged into `main`

**Comment by metanivek** [comment]
@zshipko hmm, maybe. The commit list is just a commit and a revert of the commit. I can't find any other branches that have these commits though. :detective:

**Comment by zshipko** [comment]
Oh interesting, either way I guess closing it makes sense for now :shrug:

**Pull request closed without merging**
