### PR TITLE
irmin-pack: Fix failure when computing summary in tree benchmark

### PR DESCRIPTION
**Pull request by zshipko**
This PR makes it so `./bench/irmin-pack/tree.exe` runs successfully and is able to produce a summary.

Fixes https://github.com/mirage/irmin/issues/1965

### CODE REVIEW

**Comment by metanivek** [comment]
I don't have enough context on broader implications, but either the flag also needs to change in octez (see [here](https://gitlab.com/tezos/tezos/-/blob/master/src/lib_context/encoding/context.ml#L39) and [here](https://gitlab.com/tezos/tezos/-/blob/master/src/lib_context/encoding/context_binary.ml#L39)) or the fix for this bug is somewhere deeper in the gc code.

**Comment by zshipko** [comment]
Yeah, it's very likely that there is some deeper issue but this at least gets us some potentially usable output from the tree benchmark.

**Comment by samoht** [comment]
That's a great insight but I am not convinced by the fix :-)

Could you try to trace when an empty tree is generated/written on disk? This is never supposed to happen. I also think we should remove that option and always fail hard when this happens as this is almost always due to a bug - unless I am missing something.

**Comment by zshipko** [comment]
I'm closing this for now because this PR doesn't seem to address the root of the problem and will require some additional investigation.

**Comment by zshipko** [comment]
Right after closing this I figured out the actual issue - sorry for the noise!

It looks like the store was being initialized with an empty tree in `tree.ml`: https://github.com/mirage/irmin/pull/1968/files#diff-ac9a848ef33f94ac0d84a06ad3b528d96a7b45df4ce2c699c8617f0f36154a3dL89

This PR now removes that initial empty commit and everything seems to be working - luckily this means this issue does not come from the tezos trace.

**Comment by samoht** [comment]
Saving an empty root actually seems a valid use case.  I would just make it a no-op so that empty trees are actually never persisted on disk.

**Comment by samoht** [comment]
Tracked in #1969 ; your fix is great for now :-)

**Pull request merged**
