### PR TITLE
offsets for free 2.9

### PR DESCRIPTION
**Pull request by Ngoguey42**
- [X] Clean + rebase on 2.9
- [X] Investigate broken layered store
- [ ] Need bulletproof reviews of the new offset arithmetic in IO.ml
- [X] Change back from cachecache to lru
- [X] Take care of clearing the new LRU from inside `clear`
- [x] Setup back a migration benchmark machine and bench 
- [ ] Investigate maxrss issue
- [ ] assert all bench stats look normal
- [ ] assert that this PR represents a big improvement

An finally, I'm worried about that one. I'm not sure we should merge it without a good explanation:

- [ ] Investigate the need for reads from buffer in IO.ml, the `Tbl` in `pack_store` should cover that

### CODE REVIEW

**Comment by Ngoguey42** [comment]
Migration of the 1month store with 13GB RAM free. 

Same wall time
```


Block played count *C  |                        | 0 (before) |       1 (end)
                       |                        |            |
Wall time elapsed *C   | 1m_29_150_r20.00GB     |        0us |        34min14s
                       | 1m_29_150_r20.00GB     |        0us |        32min46s  96%
                       | 1m_29_150_off_r20.00GB |        0us |        32min19s  94%
                       | 1m_29_150_off_r20.00GB |        0us |        33min58s  99%
```

The speedup on `fold` is as expected, but in exchange the `add_tree` operations (containing flushes) are 3x slower.
```

                       |                        |        cumu         | share |        min        |        max         |        avg
                       |                        |                     |       |                   |                    |
tree.fold duration (s) | 1m_29_150_r20.00GB     | 1566282.299 ms      |   76% |     0.001 ms      | 420564.056 ms      |     0.879 ms
                       | 1m_29_150_r20.00GB     | 1484721.062 ms  95% |   76% |     0.000 ms  45% | 425713.165 ms 101% |     0.833 ms  95%
                       | 1m_29_150_off_r20.00GB |  855195.283 ms  55% |   44% |     0.000 ms  43% | 137611.160 ms  33% |     0.480 ms  55%
                       | 1m_29_150_off_r20.00GB |  874062.572 ms  56% |   43% |     0.000 ms  48% | 140595.200 ms  33% |     0.490 ms  56%

add_tree duration (s)  | 1m_29_150_r20.00GB     |  365211.707 ms      |   18% |     0.000 ms      | 206186.523 ms      |     0.205 ms
                       | 1m_29_150_r20.00GB     |  357855.917 ms  98% |   18% |     0.000 ms  89% | 202269.135 ms  98% |     0.201 ms  98%
                       | 1m_29_150_off_r20.00GB |  965587.036 ms 264% |   50% |     0.000 ms 101% | 441825.867 ms 214% |     0.542 ms 264%
                       | 1m_29_150_off_r20.00GB | 1026169.255 ms 281% |   50% |     0.000 ms  86% | 469507.904 ms 228% |     0.576 ms 281%
```

The disk reads from `Raw` are as expected, but it changes nothing from the point of view of rusage.
```

                       |                        |      total     
                       |                        |                
Disk reads             | 1m_29_150_r20.00GB     |  228.904 M     
                       | 1m_29_150_r20.00GB     |  228.904 M 100%
                       | 1m_29_150_off_r20.00GB |  147.065 M  64%
                       | 1m_29_150_off_r20.00GB |  147.065 M  64%

rusage.inblock         | 1m_29_150_r20.00GB     |   92.912 M     
                       | 1m_29_150_r20.00GB     |   79.149 M  85%
                       | 1m_29_150_off_r20.00GB |   88.111 M  95%
                       | 1m_29_150_off_r20.00GB |   90.768 M  98%
```

[1m20.txt](https://github.com/mirage/irmin/files/7587249/1m20.txt)

**Comment by samoht** [comment]
> The speedup on fold is as expected, but in exchange the add_tree operations (containing flushes) are 3x slower.

Do you know why?

**Comment by Ngoguey42** [comment]
no clue

**Comment by Ngoguey42** [comment]
Closing as this is not such a big improvement

**Pull request closed without merging**
