### PR TITLE
Graphql client2

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
I've added cd4d390a3f89b715c6448ddcb7489cffd64ebd47 but all the tests still fail with:

```
[failure] resolution failed: name resolution failed
Raised at file "src/irmin-test/store.ml", line 120, characters 6-13
Called from file "src/alcotest.ml", line 285, characters 8-14
```

I'll continue to investigate...

**Comment by samoht** [comment]
Made some progress with de8d18bf366e3951935a52d39c21398975424de4 but now failing with
```
[exception] Irmin_graphql__Helper.Graphql("expected JSON text (JSON value)")
```

**Comment by zshipko** [comment]
Hmm, that error means the client might not be connecting to the server anymore. 

The tests also show a 404 error:

```
cohttp.lwt.io [DEBUG] <<<[152] {"variables":{"object":""},"query":"\n          mutation AddObject($object: String!) {\n            add_object(object: $object)\n          }\n        "}
cohttp.lwt.io [DEBUG] >>> HTTP/1.1 404 Not Found
cohttp.lwt.io [DEBUG] >>> transfer-encoding: chunked
```

**Comment by zshipko** [comment]
Ah, I got it! 

If you just change this line:
```
let uri = Uri.of_string "http://irmin"
```
to 
```
let uri = Uri.of_string "http://irmin/graphql"
```
Then it seems to be working.

**Comment by andreas** [comment]
I'm thinking about how `Irmin_graphql.Client` from this PR is affected by the custom GraphQL presentation from https://github.com/mirage/irmin/pull/643. If I read the code correctly, this PR assumes that values will be exposed as strings (i.e. values are decoded from strings), but it could be the case that the server exposes a custom, rich GraphQL object. I guess we could either try to have the client take the custom presentation into account, or maybe it's fine to restrict `Graphql_irmin.Client` to only work with values presented as strings -- in that case we should probably make a note somewhere, though.

Finally, I thought I should mention that using a GraphQL ppx could be another way to interact with the Irmin GraphQL API:

- [`mhallin/graphql_ppx`](https://github.com/mhallin/graphql_ppx) supports many (all?) GraphQL query constructs, and has seen quite active development and real-world usage. It's currently Bucklescript-focused, but there's a [work-in-progress PR](https://github.com/mhallin/graphql_ppx/pull/73) for native support.
- [`andreas/ppx_graphql`](https://github.com/andreas/ppx_graphql/network) is OCaml-oriented, but is much less featureful and mature.

**Comment by samoht** [comment]
Maybe an option would be to extend `Irmin.Contents.S` to expose richer GraphQL interfaces in the GraphQL backend?

**Comment by samoht** [comment]
Also, would it make sense to have `set`, `set_tree` (add all the command exposed by the CLI) use the high-level API with a rich query instead of using the low-level API as it is done now (I think) ?

**Comment by zshipko** [comment]
@andreas, thanks for the suggestions regarding the ppxs, I will look into both of those!

> I'm thinking about how Irmin_graphql.Client from this PR is affected by the custom GraphQL presentation from #643. If I read the code correctly, this PR assumes that values will be exposed as strings (i.e. values are decoded from strings), but it could be the case that the server exposes a custom, rich GraphQL object.

Since I haven't spent much time with the new custom content representation code I will need to experiment a bit to figure out how to resolve this situation. I guess worst case we only allow string representation (as you said), but I would really like to figure out a nice solution. 

> Maybe an option would be to extend Irmin.Contents.S to expose richer GraphQL interfaces in the GraphQL backend?

This is a possibility, I will keep it in mind when thinking about this!

> Also, would it make sense to have `set`, `set_tree` (add all the command exposed by the CLI) use the high-level API with a rich query instead of using the low-level API as it is done now (I think) ?

Yeah, that makes sense - I'm in the process of porting over the functions I wrote for the previous version of this PR, this should cover most (if not all) of the commands exposed by the CLI.

**Pull request closed without merging**
