### PR TITLE
irmin; use a more consistent scheme for Maker signatures

### PR DESCRIPTION
**Pull request by samoht**
note: I'm not totally satisfied with the resulting API conventions (that I should probably document) and with the current level of duplication in signatures, but I still think it's an improvement over the current situation.

If everyone think it is a good direction, I need to document the new convention and the breaking changes.

### CODE REVIEW

**Comment by samoht** [comment]
(note: I have a bunch of follow-up PRs which will benefit greatly of having the maker signatures look that way)

**Review by CraigFe — APPROVED** [review]

**Comment by CraigFe** [comment]
LGTM. Agreed that this is an improvement over the current state, even if it doesn't really solve the backend signature boilerplate problem.

**Comment by samoht** [comment]
I've pushed a new commit which make the signature for `Make` and `Make_ext` more consistent. Writing the CHANGELOG now..

**Review by Ngoguey42 — APPROVED** [review]
Looks good

**Comment by samoht** [comment]
Rebased and updated changes.

**Pull request merged**
