### PR TITLE
Less calls to find_value in inode

### PR DESCRIPTION
**Pull request by Ngoguey42**
This could be a big optimisation. 

I don't know how to plot fancy benchmark png yet. I will try to include those in the comments below.

Make sure you tick the `Hide whitespace changes` when viewing the diff.

### CODE REVIEW

**Comment by Ngoguey42** [comment]
Roughly down to `27.8s` from `29.7s` on `time dune exec -- bench/irmin-pack/main.exe`.

**Comment by samoht** [comment]
Can you test this on large directories and see is the speed gain if bigger?

**Comment by icristescu** [comment]
> Can you test this on large directories and see is the speed gain is more noticeable?

I'm working on adding benchmarks for this, I'll open a PR shortly.

**Comment by Ngoguey42** [comment]
I couldn't find any perf difference using `dune exec -- ./bench/irmin-pack/tree.exe --mode=large --width=10 --ncommits=100000` from #1237.
I'm investigating further

**Comment by samoht** [comment]
Try with a large `width` (e.g 10k)

**Comment by Ngoguey42** [comment]
Both setups have similar perfs. Since there was a real diff using `main.exe` i'm suspecting `tree.exe` not to use the `add` function.

```
➜  irmin bench_inodes dune exec -- ./bench/irmin-pack/tree.exe --mode=large --width=10 --ncommits=30000
+1610361518us  application Large trees mode: 30000 commits, each consisting of 2 large trees of 10 entries completed in 12.92s
+1610361547us  application Large trees mode: 30000 commits, each consisting of 2 large trees of 10 entries completed in 26.11s
+1610361574us  application Large trees mode: 30000 commits, each consisting of 2 large trees of 10 entries completed in 13.10s
+1610361590us  application Large trees mode: 30000 commits, each consisting of 2 large trees of 10 entries completed in 13.76s

➜  irmin less-find_value-in-inode dune exec -- ./bench/irmin-pack/tree.exe --mode=large --width=10 --ncommits=30000
+1610361782us  application Large trees mode: 30000 commits, each consisting of 2 large trees of 10 entries completed in 13.22s
+1610361810us  application Large trees mode: 30000 commits, each consisting of 2 large trees of 10 entries completed in 25.72s
+1610361824us  application Large trees mode: 30000 commits, each consisting of 2 large trees of 10 entries completed in 12.79s
+1610361841us  application Large trees mode: 30000 commits, each consisting of 2 large trees of 10 entries completed in 14.83s


➜  irmin bench_inodes dune exec -- ./bench/irmin-pack/tree.exe --mode=large --width=30000 --ncommits=10
+1610361612us  application Large trees mode: 10 commits, each consisting of 2 large trees of 30000 entries completed in 11.34s
+1610361626us  application Large trees mode: 10 commits, each consisting of 2 large trees of 30000 entries completed in 11.58s
+1610361640us  application Large trees mode: 10 commits, each consisting of 2 large trees of 30000 entries completed in 11.98s
+1610361681us  application Large trees mode: 10 commits, each consisting of 2 large trees of 30000 entries completed in 11.45s


➜  irmin less-find_value-in-inode dune exec -- ./bench/irmin-pack/tree.exe --mode=large --width=30000 --ncommits=10
+1610361869us  application Large trees mode: 10 commits, each consisting of 2 large trees of 30000 entries completed in 11.15s
+1610361883us  application Large trees mode: 10 commits, each consisting of 2 large trees of 30000 entries completed in 11.26s
+1610361896us  application Large trees mode: 10 commits, each consisting of 2 large trees of 30000 entries completed in 10.86s
+1610361909us  application Large trees mode: 10 commits, each consisting of 2 large trees of 30000 entries completed in 11.52s
```

**Comment by Ngoguey42** [comment]
I don't know why the length doubled on the second iterations of the first setup

**Comment by Ngoguey42** [comment]
I could get this perf diff using `main.exe` again.

```
{
  "contents_hash": 1000000,
  "contents_find": 1000000,
  "contents_add": 10,
  "node_hash": 30,
  "node_mem": 30,
  "node_add": 30,
  "node_find": 30,
  "node_val_v": 0,
  "node_val_find": 0,
  "node_val_list": 0
}
```

```
➜  irmin bench_inodes time dune exec -- bench/irmin-pack/main.exe -a 100000 -d 2 -n 10
dune exec -- bench/irmin-pack/main.exe -a 100000 -d 2 -n 10  59.65s user 7.25s system 98% cpu 1:07.79 total
dune exec -- bench/irmin-pack/main.exe -a 100000 -d 2 -n 10  38.12s user 4.19s system 99% cpu 42.566 total
dune exec -- bench/irmin-pack/main.exe -a 100000 -d 2 -n 10  36.91s user 4.04s system 99% cpu 41.150 total


➜  irmin less-find_value-in-inode time dune exec -- bench/irmin-pack/main.exe -a 100000 -d 2 -n 10
dune exec -- bench/irmin-pack/main.exe -a 100000 -d 2 -n 10  31.65s user 4.08s system 99% cpu 35.870 total
dune exec -- bench/irmin-pack/main.exe -a 100000 -d 2 -n 10  32.16s user 4.20s system 99% cpu 36.490 total
dune exec -- bench/irmin-pack/main.exe -a 100000 -d 2 -n 10  32.23s user 4.20s system 99% cpu 36.614 total
```

**Comment by Ngoguey42** [comment]
I've updated my comment above to encompass the state of the disk before the test

**Comment by icristescu** [comment]
The difference between the two benchmarks is due to different `Conf` values for the inodes. With `entries = 2` and `stable_hash = 3` I get similar benchmarks to yours:

```
(bench_inodes)> time dune exec -- ./bench/irmin-pack/tree.exe --mode=large --width=100000 --ncommits=10
Large trees mode: 10 commits, each consisting of 2 large trees of 100000 entries completed in 127.92s
Large trees mode: 10 commits, each consisting of 2 large trees of 100000 entries completed in 126.36s

(Ngoguey42-less-find_value-in-inode)>
time dune exec -- ./bench/irmin-pack/tree.exe --mode=large --width=100000 --ncommits=10 
Large trees mode: 10 commits, each consisting of 2 large trees of 100000 entries completed in 116.83s
Large trees mode: 10 commits, each consisting of 2 large trees of 100000 entries completed in 118.36s
```

Thanks a lot @Ngoguey42 for looking at these benchmarks, we should probably always run several benchmarks with different configuration values. I'll update https://github.com/mirage/irmin/pull/1237.

So the benchmarks show that this PR is an improvement, LGTM.

**Review by icristescu — APPROVED** [review]

**Comment by Ngoguey42** [comment]
@icristescu, both https://github.com/mirage/irmin/pull/1235 and https://github.com/mirage/irmin/pull/1244 additional tests are passing. Merging

**Pull request merged**
