### PR TITLE
Make fetch/pull/push results more intuitive

### PR DESCRIPTION
**Pull request by zshipko**
Instead of #683, where the documentation doesn't really help clarify the cases that much, I've updated the API to only use `` `Msg of string ``.

### CODE REVIEW

**Comment by samoht** [comment]
I agree that we should treat empty repository properly (e.g. not throw an error when it's not needed) but I'm not sure it makes sense to completely remove the error structure. But maybe there's nothing else to do than printing with these errors?

Also your patch seems to change the semantics of the return of few of the operations, do you mind giving a summary of the changes? Did you try to avoid having `No_head` on both the ok and the error side?

**Comment by zshipko** [comment]
Well the `` `No_available `` error seems misleading. It seems like it would indicate that the remote is unreachable, but really signals that the action is not supported, which seems like something you would just print rather than handle.

I guess the changes you're talking about are to `pull`/`push` where `` `No_head `` is now ignored. I agree that throwing away that information is not ideal, but hadn't thought about using `` `No_head `` in the `Ok` case. I think that sounds like it could be a nice way to preserve the existing semantics of push/pull while cleaning up the API a little.

Just to be clear, this would look something like:

```ocaml
val pull :
    db ->
    ?depth:int ->
    remote ->
    [ `Merge of Info.f | `Set ] -> 
    ([`No_head | `Success], pull_error) result Lwt.t

val push :
    db -> 
    ?depth:int -> 
    remote -> 
    ([`No_head | `Success], [ `Msg of string | `Detached_head]) result Lwt.t
```

**Comment by hannesm** [comment]
in fetch and pull, I do understand that this may result in `` `No_head ``, but how so in push? or, the other way around, let's assume I pulled an empty repository (--> `` `No_head ``), do a commit and push, that should lead to success (and not `` `No_head ``), no?

**Comment by zshipko** [comment]
You will only get `` `No_head `` on push when the local repository (the one you're pushing from) has no commits. So your example is correct, the result will be `` `Success `` since the repo is no longer empty.

**Comment by samoht** [comment]
I'm not totally sure about `No_head`. Maybe something more explicit like:

```
type pull_result = [ `Empty | `Head of commit ]
type push_result = [`Empty | `Head of commit ]
```

What do you think?

Also, I don't remember what's the `Detached_head` error means :-)

**Comment by zshipko** [comment]
Yeah, returning the commit like that seems better, I will update this.

The `Detached_head` error only occurs here: https://github.com/mirage/irmin/blob/850b8e52131611d8deb05008774ab112a71ccca3/src/irmin/sync_ext.ml#L174

**Comment by zshipko** [comment]
Hmm, these test errors just started showing up and I'm not sure why. I don't think it's specific to this branch because they can be seen both [here](https://travis-ci.org/mirage/irmin/builds/532046814?utm_source=github_status&utm_medium=notification) and [here](https://travis-ci.org/mirage/irmin/builds/532026231?utm_source=github_status&utm_medium=notification)

**Comment by zshipko** [comment]
Well, the tests are back to passing. I'm hoping the failures were related to this: https://github.com/ocaml/opam-repository/pull/14154#issuecomment-494075614

**Pull request merged**
