### PR TITLE
irmin-git: enable s390x

### PR DESCRIPTION
**Pull request by Ngoguey42**

### CODE REVIEW

**Comment by Ngoguey42** [comment]
`s390x` works again for `irmin-git`, but it doesn't with `libirmin`

**Comment by zshipko** [comment]
I just updated this PR: https://github.com/mirage/irmin/pull/2030 to make libirmin unavailable on s390x

**Comment by metanivek** [comment]
Thanks @zshipko. Closing this one.

**Comment by metanivek** [comment]
Actually, on second thought, lets keep this but rename. It should have green CI once rebased with #2030.

**Pull request merged**
