### PR TITLE
[2.10] opam: fix git lower bound

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
Similar to https://github.com/ocaml/opam-repository/pull/20589 (not sure why we missed it)

**Comment by maiste** [comment]
There seems to be a dependency problem when trying to install with the `--with-test` opam flag. Indeed, it requires the `git-cohttp-unix` package. However, the last version of this package is `3.6.0` and requires `git = 3.6.0`. As it seems this package no longer exists on the official repository (ocaml-git), shouldn't `irmin-http` stops to rely on it?
```
[ERROR] Package conflict!
  * No agreement on the version of git:
    - irmin-http >= dev -> git-cohttp-unix -> git = 3.6.0
    - irmin-unix >= dev -> git >= 3.7.0
No solution found, exiting
```

**Comment by samoht** [comment]
Thanks, I've pushed a fix.

**Review by maiste — APPROVED** [review]
Thanks!
LGTM :+1:

**Pull request merged**
