### PR TITLE
irmin-pack: Fix mmap RO opening flags

### PR DESCRIPTION
**Pull request by Ngoguey42**

### CODE REVIEW

**Comment by Ngoguey42** [comment]
Done

**Comment by metanivek** [comment]
Ah, I meant the PR description but that works too. :smile:

**Comment by icristescu** [comment]
Thanks!

**Comment by metanivek** [comment]
How to reproduce the bug that this PR fixes. From @icristescu:

- create a store with root `dir`
- set permission for all files in `dir` to readonly
- set permission for the `dir` to execute - this is needed for `stat` https://github.com/mirage/irmin/blob/f778ef1f5d277ca113700dd6689b3e94be20a490/src/irmin-pack/unix/io.ml#L97
- open the store with `readonly:true`

**Pull request merged**
