### PR TITLE
Use latest Mirage_kv.RO signature

### PR DESCRIPTION
**Pull request by samoht**
It's only RO for now, but it is already showing a few issues. The `last_modified` function is very naive and will iterate over the full store (which is not really optimal :p)

I plan to add the new RW functions too and see how it goes :-)

/cc @linse

### CODE REVIEW

**Comment by hannesm** [comment]
this branch does not compile for us, We fixed some issues in https://github.com/hannesm/irmin/commit/e71637bbe9fe867faff446842eba12032bda1c4e - but since we don't have a deep understanding of irmin internals, we don't know how to properly fix them.

The most recent error is:
```
File "src/irmin/irmin.ml", line 1:
Error: The implementation src/irmin/irmin.ml
       does not match the interface src/irmin/.irmin.objs/irmin.cmi:
       ...
       At position module type S = <here>
       The value `write_error_t' is required but not provided
       File "src/irmin/irmin.mli", line 2933, characters 2-39:
         Expected declaration
       At position module type S = <here>
       The value `with_tree_exn' is required but not provided
       File "src/irmin/irmin.mli", line 2748, characters 2-252:
         Expected declaration
```

any chance anyone more familiar with irmin could have a look into rebasing + getting this branch to work? thanks!

**Comment by zshipko** [comment]
I just had a quick look at rebasing this branch but there have been too many conflicting updates for me to handle it since I'm not that familiar with these changes in particular -- it seems like @samoht is the one who will be able to get this working if anyone can.

**Comment by samoht** [comment]
Rebased. Note that this is largely untested...

**Comment by linse** [comment]
Hallo! We added a sync (git push) to happen after the set, remove and batch operation in the KV interface. This is debatable, maybe the sync should only happen on `batch` and we should remove our changes for `set` and `remove`? Let's discuss!

**Comment by samoht** [comment]
Sync on batch sounds better than sync on set. An other option is to either add a new function in the KV_RW api for `fsync`-like operations, or use one special file in the KV store where you could write to to make a sync (a la 9p). I'm not very fond of both options, so probably adding this to batch is ok..

**Comment by hannesm** [comment]
now that mirage-kv (and mirage-kv-lwt) 2.0.0 is in opam repository, i think this can be merged. (may need some lower bounds in the opam file).

**Comment by zshipko** [comment]
I just tested this branch with  the new `mirage-kv-lwt` release and it seems to be working correctly!

@samoht: is there anything further work needed on this branch? If not I can add the lower-bound for `mirage-kv-lwt` and merge it.

**Pull request merged**
