### PR TITLE
irmin: separate set/test_and_set/merge functions to update the store

### PR DESCRIPTION
**Pull request by samoht**
The function now return a result type, but also add _exn variants which
raise an exception.

### CODE REVIEW

**Comment by zshipko** [comment]
These changes definitely look like a major improvement!

I have no problem updating the tutorials to match this new interface -- I can start updating the tutorials today and will let you know if I come across any issues.

**Comment by zshipko** [comment]
I've just gotten started modifying the tutorial and am not sure if I'm misunderstanding the changes to `with_tree`, but when I run the following example:

```ocaml
open Lwt.Infix
module Mem_store = Irmin_unix.Git.Mem.KV(Irmin.Contents.String)

let config = Irmin_mem.config ()

let transaction_example =
Mem_store.Repo.v config >>= Mem_store.master >>= fun t ->
let info = Irmin_unix.info "example transaction" in
Mem_store.with_tree_exn t [] ~info ~strategy:`Set (fun tree ->
    let tree = match tree with Some t -> t | None -> Mem_store.Tree.empty in
    Mem_store.Tree.remove tree ["foo"; "bar"] >>= fun tree ->
    Mem_store.Tree.add tree ["a"; "b"; "c"] "123" >>= fun tree ->
    Mem_store.Tree.add tree ["d"; "e"; "f"] "456" >>= Lwt.return_some)

let () = Lwt_main.run transaction_example
```
I get this error:

```
Fatal error: exception (Failure
  "with_tree_exn: Failure after 13 attempts to retry the operation: Too many attempts.")
```

**Comment by samoht** [comment]
Ha yes sorry, it was a stupid typo, I've just fixed it.

**Comment by zshipko** [comment]
Great! I will finish updating the tutorial over the next few days and let you know if I encounter any other issues.

**Comment by samoht** [comment]
I've added a few tests for `Irmin.with_tree` and fixed a few more issues. Hopefully all is working fine now :-)

**Comment by samoht** [comment]
Great! Merging, then.

**Pull request merged**
