### PR TITLE
irmin: Irmin.Make ensures that there is no hash collision

### PR DESCRIPTION
**Pull request by samoht**
On top of #1308 

Might probably need a bit of documentation if we go that way.

### CODE REVIEW

**Comment by Ngoguey42** [comment]
I didn't consider this solution :) That's much simpler than my 2 drafts.

One small loophole: you're not prefixing the pre_hash of `Chunk.t`.

Also, how would proceed with prefixing in irmin-pack? Especially regarding the unstable prehash, I think this would require bringing back the `Conf.prefix_unsable_pre_hash` parameter of #1305. Unless you think it's okey not to prefix the unsable prehash and instead rely on the initial byte from the variant, but I'm not a fan of that solution.

**Comment by samoht** [comment]
You are right, `irmin-pack` use `Irmin.Of_private` and so doesn't prevent pre_hash collisions. And you are also right: we need to keep Tezos working and so we need to find a way where we keep the actual behaviour for stable trees but have safer default when not using custom commit/nodes/blobs. So again, maybe just do this in `Irmin_pack.Make` ?

**Comment by samoht** [comment]
I've pushed a fix for `Irmin_pack`. I am still not super happy with the current solution. I think I'll try to experiment with adding explicit prefix hashes in `repr` API instead.

**Comment by Ngoguey42** [comment]
I have 2 concerns:
- I'm afraid that in the current state, `irmin-chunk` is not protected against pre-hash collisions.
- To create a store, the user is asked for a Contents definition and a Hash algorithm, they will not expect the store to secretly insert a byte in the pre-hash of their blobs.

**Comment by samoht** [comment]
> To create a store, the user is asked for a Contents definition and a Hash algorithm, they will not expect the store to secretly insert a byte in the pre-hash of their blobs.

This is already not the case with the Git backend and nobody really care ; I think it's fine as long as we document how the final hash is computed.

**Comment by samoht** [comment]
> I think I'll try to experiment with adding explicit prefix hashes in repr API instead.

I've done this and it's not a good idea (or at least I haven't found the right API). 

So we should probably merge something simpler (like what I've done in that PR).

**Comment by icristescu** [comment]
Closing, as this was solved by https://github.com/mirage/irmin/pull/1715

**Pull request closed without merging**
