### PR TITLE
Add `no-migrate` to irmin-pack config, update checks to work with V3

### PR DESCRIPTION
**Pull request by zshipko**

### CODE REVIEW

**Comment by Ngoguey42** [comment]
The `files` field has no obvious meaning. It seems it can be removed https://github.com/mirage/irmin/commit/06c77214401d6d77a3225728f6ff511d9f92af30

Also, `Checks` make use of `Traverse_pack_file` which still needs so use the new io.

**Comment by zshipko** [comment]
I've removed the `files` field for now and updated `traverse_pack_file.ml` to use `File_manager` - since the semantics of the `read_exn` changed a bit, the updates to [`refill_buffer`](https://github.com/mirage/irmin/pull/1893/files#diff-3ba6530573b1a504e74e6ad4e51dd45fe92c02527f881ec6042b38c07277f3b6R192) were a little confusing and could probably use a review.

**Comment by icristescu** [comment]
The test for traverse pack file was not testing a buffer refill. I modified the test in https://github.com/mirage/irmin/pull/1893/commits/2836b2acc9cfa1f085e9c042f03068a983e65a50 maybe there is a cleaner way to do this.

**Review by Ngoguey42 — APPROVED** [review]

**Review by icristescu — APPROVED** [review]
Thanks!

**Pull request merged**
