### PR TITLE
Replace anonymous modules with named ones

### PR DESCRIPTION
**Pull request by icristescu**
.. to fix opam pins.

### CODE REVIEW

**Comment by samoht** [comment]
I think it would be better to name these bindings instead of just removing them :-) It's super useful to check that we stay compatible with Irmin core signatures.

**Comment by CraigFe** [comment]
Elsewhere we've called these things of the form `Foo_is_a_foo`: https://github.com/mirage/irmin/blob/master/src/irmin-pack/irmin_pack.ml#L72-L76

I'm still curious about why our PPX stack is constraining us in this way though.

**Comment by icristescu** [comment]
> Elsewhere we've called these things of the form `Foo_is_a_foo`: https://github.com/mirage/irmin/blob/master/src/irmin-pack/irmin_pack.ml#L72-L76

Thanks for the pointer, I renamed them.

**Review by CraigFe — APPROVED** [review]
Thanks!

**Pull request merged**
