### PR TITLE
irmin-git: fix spurious warning when writing to a new branch

### PR DESCRIPTION
**Pull request by CraigFe**
This avoids a warning when running the Irmin CLI example in the README:

```diff
 $ echo "root: ." > irmin.yml
 $ irmin init
 $ irmin set foo/bar "testing 123"
-irmin: [ERROR] Reference refs/heads/main not found.
 $ irmin get foo/bar
 testing 123
```

### CODE REVIEW

**Comment by CraigFe** [comment]
Might be nice to have `ocaml-git` expose a `read_opt` that doesn't consider "`Reference_not_found _`" to be an error. CC @dinosaure; happy to make a PR if you agree.

**Comment by CraigFe** [comment]
Personally I'm happy to merge this as-is, provide the PR to `ocaml-git`, then you can release the change whenever is convenient (in combination with other changes) and we'll upgrade then.

**Comment by dinosaure** [comment]
Be aware that mirage/ocaml-git#533 was merged and released via `git.3.6.0`.

**Review by zshipko — APPROVED** [review]
Looks good! I think this is probably worth merging here, rather than requiring a new ocaml-git release.

**Comment by CraigFe** [comment]
Thanks all :-) Merging.

**Pull request merged**
