### PR TITLE
Catch top-level exception in watch handlers

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by talex5** [comment]
LGTM (though slightly odd that you store a `protect` closure with every watch rather than calling `protect` when the callback is used).

**Comment by samoht** [comment]
Updated.

**Comment by talex5** [comment]
Interesting Travis failure: https://travis-ci.org/mirage/irmin/jobs/173904997

**Comment by samoht** [comment]
The TravisCI error is a race between updates and removes. I am not sure to understand fully how this is possible but I will add some synchronisation points in the tests to avoid it.

**Comment by samoht** [comment]
After more investigation, things are not much clearer. The watch callback seems to fire twice for some unknown reason:

```
test.native: [INFO] Writing test-db/refs/master (test-db/tmp/master744e2cwrite)
test.native: [DEBUG] notify-all[138.51]: firing!
test.native: [DEBUG] notify-all[138.51]: firing!
[...]
test.native: [INFO] Writing test-db/refs/master (test-db/tmp/masterc88b09write)
test.native: [DEBUG] notify-all[138.51]: firing!
test.native: [DEBUG] notify-all[138.51]: firing!
```

**Comment by samoht** [comment]
I've added more debugging code, let see if that helps..

**Pull request merged**
