### PR TITLE
Update headers

### PR DESCRIPTION
**Pull request by samoht**
I've tried to update the copyright notice with the right names but I have most probably made a few mistakes. Please add your name if you think it should appear on a file!

/cc @icristescu @pascutto @CraigFe @Ngoguey42 @zshipko 

@andreas for the GraphQL files, what name address do you want me to use?

### CODE REVIEW

**Review by Ngoguey42 — APPROVED** [review]

**Comment by icristescu** [comment]
Would it make sense to have only `(* Copyright (c) 2020 Tarides <contact@tarides.com>                          *)` instead of individual names? our names are already in the commits maybe that's enough?

**Review by zshipko — APPROVED** [review]

**Comment by samoht** [comment]
Yes it's fine to add `Copyright Tarides` for new files - but we cannot rewrite the history and add copyright to existing files (created before Tarides existed). I'll do this for irmin-pack then.

**Review by icristescu — APPROVED** [review]
Thanks!

**Review by avsm — APPROVED** [review]
LGTM

**Pull request merged**
