### PR TITLE
[RFC] Use sha_1 from uuidm to avoid Nocrypto, which requires C

### PR DESCRIPTION
**Pull request by talex5**
This is needed to use Irmin with js_of_ocaml.

Not sure if this function should be moved to a separate package, or whether the license should be changed to match Irmin's. If it stays here, we could change it to operate on cstructs directly rather than converting to a strings.

/cc @dbuenzli

### CODE REVIEW

**Comment by samoht** [comment]
Travis is failing because you need to regenerate the `_oasis` auto-crap. I'll do it after merging.

About that patch: SHA1 is also used in the Git implementation and I wanted to be able to functorised `ocaml-git` relatively to the SHA1 implementation (see https://github.com/mirage/ocaml-git/issues/69). That's not the same concern, but could be useful to port Irmin's Git backend to js_of_ocaml. Not sure it is worth having a separate package though, as by default people will want to have the fast SHA1 version anyway.

And I also agree with the string/cstruct conversion.

**Comment by talex5** [comment]
Good point. I've fixed the `_oasis` file anyway, as I'm using this branch in my Travis build. It now fails to build trying to installed `conf-gmp` for some reason though.

**Comment by samoht** [comment]
Seems that the Travis scripts do not install the depext for the test dependencies ...

**Comment by samoht** [comment]
@talex5 can you add `nocrypto` in the DEPOPTS in `travis.yml`? This should work-around the bug in `opam-depext`....

**Comment by talex5** [comment]
Doesn't seem to help...

**Comment by samoht** [comment]
Superseded by #185

**Pull request closed without merging**
