### PR TITLE
Remove Git_paf and lint dependencies according to the last version of Git

### PR DESCRIPTION
**Pull request by dinosaure**
Same as #1632 for 2.10

### CODE REVIEW

**Comment by samoht** [comment]
Had a quick chat with @dinosaure, ocaml-git 3.7 has not been released yet so we can't merge this for the irmin 2.10 release. Will be part of the next one (2.11 or 3.00) early next year.

**Comment by dinosaure** [comment]
Note that `git.3.7.0` was released - we still have a chance to merge this PR 🙂 .

**Comment by maiste** [comment]
The tests work on my machine and I was able to install it with `git 3.7`.
@samoht do you think we can still merge it in `2.10`?
LGTM :+1:

**Comment by samoht** [comment]
I'll merge this once the CI is green (I've restarted to 2 failing tests).

**Comment by samoht** [comment]
Could you also add a CHANGELOG entry?

**Comment by samoht** [comment]
Thanks

**Pull request merged**
