### PR TITLE
Fix cascading fails

### PR DESCRIPTION
**Pull request by Ngoguey42**

### CODE REVIEW

**Comment by CraigFe** [comment]
Perhaps we want to at least attempt to close the handle as well (and catch any exceptions raised while doing that), so as to not leak memory / file descriptors from a failing test?

Avoiding the call to `clear` is great, and unblocks https://github.com/mirage/irmin/pull/1534, which can then temporarily drop support for `clear` in `irmin-pack`.

**Comment by Ngoguey42** [comment]
> Perhaps we want to at least attempt to close the handle as well

I tried to do that at some point, but passing `repo` to `clean` wasn't a straightforward change. 

Since `run` is responsible for instantiating `repo`, shouldn't it also be responsible for closing it (instead of trying to do that from `clean`)? https://github.com/mirage/irmin/blob/b1a2e683c3fb59c579e2bb49f021246178558fea/src/irmin-test/common.ml?ts=4#L233-L242

Side node: All the tests in https://github.com/mirage/irmin/blob/b1a2e683c3fb59c579e2bb49f021246178558fea/src/irmin-test/store.ml call `run` exactly once and finish with `B.Repo.close repo`

**Comment by CraigFe** [comment]
> Since run is responsible for instantiating repo, shouldn't it also be responsible for closing it (instead of trying to do that from clean)?

This makes sense to me.

**Review by CraigFe — APPROVED** [review]

**Comment by Ngoguey42** [comment]
I've just added closes` in `run`

**Pull request merged**
