### PR TITLE
4.08.0 compat

### PR DESCRIPTION
**Pull request by avsm**
@andreas just one question here about the seemingly redundant Lazy force

### CODE REVIEW

**Comment by andreas** [comment]
The forced expression has side effects, so it’s actually not redundant. I understand why it would seem so though, and I’ve been thinking about how to improve the API for chains of mutually recursive GraphQL types..

**Comment by avsm** [comment]
Thanks for the clarification! In this case though, the removed line with the warning:

```
let _ = Lazy.force contents_as_node
```

evaluates to a closure -- will this actually have side effects?

**Comment by andreas** [comment]
Yes, here’s the source: https://github.com/andreas/ocaml-graphql-server/blob/master/graphql/src/graphql_schema.ml#L507

The approach is inspired by how Ctypes implements unions. The API works quite well when the union is not part of a mutually recursive structure, but has this wart when it is.

**Comment by avsm** [comment]
Thanks again for the clarification; I've just disabled the partial application warning in that file for now. PR should be ok to merge once CI passes @samoht

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
