### PR TITLE
Rewrite README.md

### PR DESCRIPTION
**Pull request by maiste**
This PR attempts to improve the `README.md`, following [gospel](https://github.com/ocaml-gospel/gospel/blob/main/README.md) model. It changes the following things:
- Add Irmin logo
- Remove duplicate link to the documentation
- Add a release shield
- Remove  `opam install` really specific case
- Uniformise the header management

### CODE REVIEW

**Comment by maiste** [comment]
@pascutto, I've updated the README following most of your suggestions. I'm not sure why we'd like to remove the __development__ section as it allows to gain time to developers (while the new _irming.org_ website isn't ready). What was your motivation about it?

**Comment by maiste** [comment]
@Ngoguey42 @pascutto so I guess I can merge it?

**Comment by Ngoguey42** [comment]
LGTM :)

**Review by pascutto — APPROVED** [review]
Yes, please do :)

**Comment by maiste** [comment]
Thanks for the review and the suggestions :)

**Pull request merged**
