### PR TITLE
irmin-bench: use a JSON output format

### PR DESCRIPTION
**Pull request by CraigFe**
... dropping the dependency on Notty in favour of something more panda-friendly.

### CODE REVIEW

**Comment by CraigFe** [comment]
Here's an example of the new output format:

```
bench_name,metric,value
/bin/bytes<1024>/dec,major-allocated (words),0.000002
/bin/bytes<1024>/dec,minor-allocated (words),153.002046
/bin/bytes<1024>/dec,monotonic-clock (ns),209.424714
/bin/bytes<1024>/enc,major-allocated (words),258.009646
/bin/bytes<1024>/enc,minor-allocated (words),301.013982
/bin/bytes<1024>/enc,monotonic-clock (ns),1369.890530
/bin/hash/dec,major-allocated (words),0.000034
/bin/hash/dec,minor-allocated (words),6.000149
/bin/hash/dec,monotonic-clock (ns),14.920763
/bin/hash/enc,major-allocated (words),0.001193
/bin/hash/enc,minor-allocated (words),32.000523
/bin/hash/enc,monotonic-clock (ns),53.860264
...
```

**Comment by pascutto** [comment]
Thank you! 

I'm wondering if CSV is the good format here. 
The CI that is being set up for `index` requires JSON results to be processed, afaic; if we use CSV here, will we have to move to JSON later to enable the CI here?
I think we should try to unify those formats as much as possible.
/cc @MagnusS @gs0510 @icristescu, what are your views on this?

Besides the format choice, perhaps that can be upstreamed as a default reporter in bechamel? /cc @dinosaure

**Comment by CraigFe** [comment]
>  The CI that is being set up for `index` requires JSON results to be processed, afaic; if we use CSV here, will we have to move to JSON later to enable the CI here?
> I think we should try to unify those formats as much as possible.

My view on this is that practically any standard format is better than the Notty output. I'm not sure how stable the current JSON format in the benchmarking pipeline is. In any case I think it's best for benchmarks to emit that format using a little library rather than each bench suite implementing its own serialiser for the format. Perhaps now is the time for us to write that library; perhaps not. (I let @gs0510 and @MagnusS be the judges of that.)

Regardless, using a CSV format here is immediately useful for being able to graph our recent performance improvements, so I think is worth merging. I'm happy to make a follow up PR to switch to a more standard format as and when that becomes available.

**Comment by avsm** [comment]
Agreed. Let's merge this to also unblock Windows builds  (which don't work with notty), and subsequently refine the precise machine format used in another PR.

**Comment by dinosaure** [comment]
> Besides the format choice, perhaps that can be upstreamed as a default reporter in bechamel? /cc @dinosaure

Currently on my TODO list :+1:

**Comment by MagnusS** [comment]
The output format used by the benchmarking pipeline should be relatively straight forward and is similar to your CSV output - it should also be panda friendly. It's documented in https://github.com/gs0510/index-benchmarks#benchmarks-format:

```
{
  "results" : [
    {
      "name": benchmark1,
      "metrics": {
        "<name of result 1>": "<result 1>",
        "<name of result 2>": "<result 2>",
        ...
      },
     ...
    }
  ]
}
```

Here's an example of what it looks like, taken from mirage/index: https://gist.github.com/gs0510/9ef5d47582b7fbf8dda6df0af08537e4

As the format just requires a few known key names in the output ("results" array with "name" and "metrics" keys) I wouldn't think this needs a separate library to produce for now (except a json library), although it could be useful later to make the format easier to change.

**Comment by CraigFe** [comment]
I experimented with using the standard format (in https://github.com/mirage/irmin/commit/849c7b1a651bf011391e0aa9259dba81cada86bf), but can't find a good solution for loading this format into a pandas data-frame quickly (although I'm sure it's possible with a more complex solution).

For now, let's go with the CSV format and revise it to the shared format at a later date once there are shared tools to make it worthwhile.

**Comment by MagnusS** [comment]
I don't mind merging this as is for now, but loading the data into a data frame seems to work fine for me in python3 with a call to `read_json` (data.json taken from gist above, with config section removed). What was the issue you ran into?

```
>>> import pandas as pd
>>> df = pd.read_json("data.json")
>>> print(df)
                                             results
0  {'name': 'replace_random', 'metrics': {'time':...
1  {'name': 'find_random_ro', 'metrics': {'time':...
2  {'name': 'find_random_rw', 'metrics': {'time':...
3  {'name': 'find_absent_ro', 'metrics': {'time':...
```

**Comment by CraigFe** [comment]
That data frame isn't very well-formed, since it's a single column `results` with no rows (apart from the default index), and each entry is a JSON string that hasn't been processed in any way.

`read_json` takes a number of "orient" options that give some control over how the JSON format is mapped into rows and columns of a data frame, but I think none of them is sufficiently expressive to handle this case. (Even when first removing the `results` indirection as I tried [here](https://github.com/mirage/irmin/commit/849c7b1a651bf011391e0aa9259dba81cada86bf#diff-8c4ae2c73c901b477574d99295faeed4R5)).

**Comment by MagnusS** [comment]
@CraigFe ah - that's annoying, I didn't notice that. Thanks for trying it out. Fwiw it seems a solution to the nested json data might be to use `json_normalize` instead of `read_json`, something like

```
d = json.load(f)
df = pd.io.json.json_normalize(d['results'])
```

**Comment by CraigFe** [comment]
Aha! Nice find; thanks.

```
                                        name  metrics.major-allocated (words)  metrics.minor-allocated (words)  metrics.monotonic-clock (ns)
0                       /bin/bytes<1024>/dec                              0.0                            201.0                        3363.0
1                       /bin/bytes<1024>/enc                            258.0                            349.0                        5456.0
2                              /bin/hash/dec                              0.0                             54.0                        2109.0
3                              /bin/hash/enc                              0.0                             80.0                        3535.0
4            /bin/int/char (0 <= b <= 7)/dec                              0.0                             68.0                        1713.0
5            /bin/int/char (0 <= b <= 7)/enc                              0.0                             86.0                        3913.0
6          /bin/int/long (16 <= b <= 32)/dec                              0.0                             74.0                        2026.0
...
```

I've added a commit that switches to the JSON format instead.

**Pull request merged**
