### PR TITLE
irmin-git: add pin-depends to ocaml-git master

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Review by CraigFe — APPROVED** [review]

**Comment by samoht** [comment]
I've also added `pin-depends` for `carton-git` and `decompress`.

**Comment by CraigFe** [comment]
I would expect you to need to add pin-depends on every package we use in the `ocaml-git` repository, since they have `=version` constraints.

**Comment by dinosaure** [comment]
I will do a release next week on my side.

**Comment by samoht** [comment]
@dinosaure: yes don't worry, there is no rush!

**Pull request merged**
