### PR TITLE
Re-enable Appveyor CI

### PR DESCRIPTION
**Pull request by CraigFe**
Fix https://github.com/mirage/irmin/issues/963.

Currently a draft as there are no changes... The name of this branch should trigger Appveyor CI on `master` so we can se what problems currently exist.

### CODE REVIEW

**Comment by CraigFe** [comment]
The CI jobs have now been queued for 30 minutes without starting.... Not a good start :confused:

**Comment by samoht** [comment]
Still no sign of appveyor :-/ Maybe faster to add windows workers to the CI :p

**Comment by CraigFe** [comment]
Passed after ~3 hours (with 45 minutes of actual CI time). That suggests that #963 might have fixed itself, but I'm not sure I want to add a 3 hour CI loop to the repository.

What does everyone else think?

**Comment by samoht** [comment]
A ~3h feedback loop is way too long. I'm thinking of ditching Travis support out instead to only keep the fast feedback loop.

Is there anything that Travis is doing here that ocaml-ci is not doing yet?

**Comment by CraigFe** [comment]
> Is there anything that Travis is doing here that ocaml-ci is not doing yet?

Yes. `ocaml-ci` does not install packages and run tests separately for each package as Travis does. This means that Travis ends up catching quite a lot of Opam metadata bugs that we would otherwise only find out about during the release: e.g. https://github.com/mirage/irmin/pull/1064.

**Comment by CraigFe** [comment]
Closing this as it doesn't seem likely that we'll be re-adding AppVeyor any time soon. We can purge it completely once OCaml-CI has Windows support.

**Pull request closed without merging**
