### PR TITLE
Convert to use Logs and new Git API

### PR DESCRIPTION
**Pull request by talex5**
Tried to upgrade to the latest git, but it had some API changes. As the string-based pretty printers have turned into formatters, I also switched to using the Logs library.

### CODE REVIEW

**Comment by talex5** [comment]
(note: Travis is failing because this depends on the Git version of ocaml-git)

**Comment by samoht** [comment]
Sorry I completely missed that PR :-/

Thanks!

**Comment by samoht** [comment]
Can you add `PINS=ocaml-git` to `.travis-ci.yml` to make Travis happy?

**Comment by talex5** [comment]
Done. Travis now happy :-)

**Comment by samoht** [comment]
Great, thanks!

**Pull request merged**
