### PR TITLE
Update CI runner versions

### PR DESCRIPTION
**Pull request by CraigFe**
- test Irmin core on 4.06
 - update Windows CI version number to match equivalents on Travis CI

### CODE REVIEW

**Comment by pascutto** [comment]
I was thinking we could also add runners for lower and upper bounds for every packages, but that might be too many runners.
If we don't do that, I suggest all backends run the oldest supported version of the compiler, so we can detect more easily if we break something.

**Comment by samoht** [comment]
Yes the opam file should reflect the lowest bound. We should also try to test some packages with the most recent version of the compiler to detect breakage early.

**Comment by samoht** [comment]
Could you rebase on master? For the lower bound in opam files: they are necessary only if the package actively not build on the given version -- if it's a transitive dependencies (in that case because of one of the mirage dependencies) let not add it ; the constraint solver will give the proper error message to our users.

**Comment by CraigFe** [comment]
> For the lower bound in opam files: they are necessary only if the package actively not build on the given version -- if it's a transitive dependencies (in that case because of one of the mirage dependencies) let not add it

Could you clarify that? Do you mean that the lower bound should denote the minimal OCaml version necessary to compile the package itself (without dependencies)? What about transitive dependencies with the Irmin packages themselves?

**Comment by samoht** [comment]
Sorry I was not clear: what I meant is that we try to add bounds only when the error comes from the current package, not its dependencies. Which means that if in the future one of the dependency is fixed to work with an older version of OCaml, there is nothing to change to compile the current package.

**Pull request merged**
