### PR TITLE
V1.Kv_ro is gone, use mirage-kv instead

### PR DESCRIPTION
**Pull request by hannesm**
mirage-runtime is superfluous now here

### CODE REVIEW

**Comment by hannesm** [comment]
travis failure in reverse dependency git, fixed by https://github.com/mirage/ocaml-git/pull/181

**Comment by hannesm** [comment]
@samoht you noticed this as well (and https://github.com/mirage/mirage-dev/issues/292)?

**Comment by samoht** [comment]
yes, thanks for the PR. I am still trying to fix ocaml-git revdeps, but I hope to look at irmin's PRs soon.

**Comment by hannesm** [comment]
merged via #395

**Pull request closed without merging**
