### PR TITLE
dune build @fmt

### PR DESCRIPTION
**Pull request by samoht**
Using the latest dev version of ocamlformat 233b31f2

### CODE REVIEW

**Comment by gpetiot** [comment]
Does every change look alright to you? Maybe `doc-comments=before` would reduce the diff a bit.

**Comment by samoht** [comment]
Rebased

**Comment by pascutto** [comment]
We might want to use version 0.11 here

**Comment by CraigFe** [comment]
Also perhaps this would go faster if we did it in phases? e.g. all the non-Irmin-pack stuff first, then we can finish by formatting Irmin-pack whenever there are fewer PRs going?

Would be nice to get this through regardless.

**Comment by samoht** [comment]
Updated to 0.11. I'll merge it later today.

**Pull request merged**
