### PR TITLE
irmin-graphql: Bump graphql-cohttp to 0.12.1

### PR DESCRIPTION
**Pull request by andreas**
Waiting for https://github.com/ocaml/opam-repository/pull/13773 to be merged...

### CODE REVIEW

**Comment by zshipko** [comment]
This error on CI seems to be out of the ordinary: https://travis-ci.org/mirage/irmin/jobs/512928463#L3876

**Comment by samoht** [comment]
That's indeed very weird:

```
# File "graphql_parser/src/graphql_parser.ml", line 1, characters 5-11:
# Error: Unbound module Result
#     ocamlopt graphql_parser/src/.graphql_parser.objs/native/graphql_parser.{cmx,o} (exit 2)
```

**Comment by andreas** [comment]
I made a mistake in the opam file of `graphql_parser` (https://github.com/ocaml/opam-repository/pull/13803). Can we try rerun CI?

**Comment by samoht** [comment]
CI is restarted.

**Pull request merged**
