### PR TITLE
bench/irmin-pack/tree.exe: respect arguments from CLI

### PR DESCRIPTION
**Pull request by zshipko**
Fixes a few places where the configured `width` and `depth` values are being overwritten

### CODE REVIEW

**Comment by Ngoguey42** [comment]
This was done one purpose in #1269. My understanding is that the `--mode quick` and `--mode slow` suites are reference suites that shouldn't be tweaked, in order to keep consistency amongst runs.

The `--mode trace`, `--mode large` and `--mode chains` are available for customised runs.

**Comment by samoht** [comment]
If possible, it's worth allowing the default configuration to be overwritten when explicitely set on the CLI.

**Comment by Ngoguey42** [comment]
That's possible. In that case I think we should remove all the parameters override too.

**Comment by samoht** [comment]
What parameter overrides?

I guess you want something like this:
```
$ ./bench.exe --mode quick # same as today
# ./bench.exe --mode quick --depth 10 # overwrite depth for the quick mode
```

**Comment by Ngoguey42** [comment]
`depth` and `width` are not the only 2 parameters that can't be changed from the CLI, e.g. `ncommits` and `nlarge_trees` from the CLI are also ignored

**Comment by Ngoguey42** [comment]
For `./bench.exe --mode quick --depth 10` one can run `./bench.exe --mode large --depth 10`, which will also only run the `large` bench and not the 2 others.

**Comment by zshipko** [comment]
I removed some more parameter overrides, though I am only using `depth` and `width` so I'm not completely familiar with the others - for example `ncommits_trace` defaults to 10000 in one case and 13315 in most others. These change do no preserve that configuration, if that's an issue then maybe we can remove that as a CLI parameter?

**Comment by Ngoguey42** [comment]
We need `ncommits_trace` as a CLI parameter, and I would say we need the default value to be different between the quick/slow modes (cc @icristescu ).

There is a problem with the `store_type` parameters in your diffs. You should either override it the same way as `inode_config` or call the right`.run*` functions (as in the custom modes).

**Comment by zshipko** [comment]
Alright, I just added those missing `inode_config` fields and made it so `mode` determines the default value for `ncommits_trace`, let me know if I missed anything.

**Review by Ngoguey42 — APPROVED** [review]
Sounds good

**Pull request merged**
