### PR TITLE
Split out test suite into its own opam package

### PR DESCRIPTION
**Pull request by zshipko**
I tried to make this as stright-forward as possible without having to modify the existing tests.

Let me know if you can think of any improvements!

### CODE REVIEW

**Comment by samoht** [comment]
That looks great, thanks!

Not sure to remember exactly what the type `kind` is used for. This would need probably needs some documentation as I am not sure what an `irmin-test` user should use for this. If I remember correctly, that's just used for pretty-printing, so maybe having a string here would be enough (but needs to double check).

**Comment by zshipko** [comment]
Yeah, I wasn't sure what a few things were, but decided to include them if they looked useful.

I can investigate what `kind` is used for and add a comment - it is better if I know this stuff anyway.

**Comment by zshipko** [comment]
It looks like `kind` is used once, [here](https://github.com/zshipko/irmin/blob/686a507d492cee5533b30f5163b88e6d854e71b9/src/irmin-test/test_store.ml#L320).

**Comment by samoht** [comment]
That seems a bit outdated and should now be working for all backend I think.

**Comment by zshipko** [comment]
If I remove the `kind` type then it triggers [this](https://github.com/zshipko/irmin/blob/686a507d492cee5533b30f5163b88e6d854e71b9/src/irmin-test/test_common.ml#L68) exception on non-git backends. However, I can just have this return the expected string instead of failing, if you think that makes sense.

**Comment by samoht** [comment]
I am not sure why we need that function anymore (even in the Git backend). We should use just https://mirage.github.io/irmin/irmin/Irmin/Info/index.html#val-author in every case.

**Comment by zshipko** [comment]
Okay, I've now removed the `author` function from Test_S and the `kind` type.

**Comment by samoht** [comment]
LGTM. Thanks!

**Pull request merged**
