### PR TITLE
Preview: upgrade to ocamlformat.0.17.0

### PR DESCRIPTION
**Pull request by gpetiot**
This is a preview of the not-yet-released ocamlformat.0.17.0, please wait until the package is published in opam to merge this PR.

### CODE REVIEW

**Review by pascutto — COMMENTED** [review]
Thank you!
I think both these changes are regressions, particularly `(x :: c) @ acc` being changed to `x :: c @ acc`, as it was a nice disambiguation imo

**Comment by CraigFe** [comment]
The wrapping change probably isn't a regression because the line was occupying 81 columns before. Agreed that the disambiguation was nice.

**Comment by pascutto** [comment]
> The wrapping change probably isn't a regression because the line was occupying 81 columns before.

Sorry for the noise, I admit I didn't check before commenting.

**Comment by CraigFe** [comment]
Rebased.

**Comment by CraigFe** [comment]
I'm not thrilled with this change, but we might as well upgrade now that the CI is happy. Thanks!

**Pull request merged**
