### PR TITLE
Merge irmin-graphql client

### PR DESCRIPTION
**Pull request by zshipko**
This PR adds `Irmin_graphql.Client` and moves the GraphQL server code into `Irmin_graphql.Server`. It also adds tests using the GraphQL client and server. Every client function has a corresponding test now! (I'm not sure, but I may continue to add more tests in another PR if time permits)

This is one of the few items still blocking the 2.0 release, so it will be nice to have this merged so I can focus on testing and documentation.

### CODE REVIEW

**Comment by zshipko** [comment]
Hm, it looks like everything is building correctly now, but the tests that access outside URLs are failing. Any idea why these errors are happening on travis-ci but not locally? Is it a missing dependency or something?

**Comment by avsm** [comment]
Those tests are probably failing due to them being run inside the opam 2 sandbox, which prevents external network access during the build phase.  So the fix is to either fetch those remote resources locally in Travis before the build, or to rename the Travis check to a sandbox check. It would be preferable to do the 'fetch the resources locally' fix so that we retain good test coverage in CI.

**Comment by zshipko** [comment]
Ah that makes sense, thanks!

**Comment by zshipko** [comment]
@avsm What is the best way to detect the opam sandbox? I think I have a good way to pre-fetch the remote resources, however it would still be nice to be able to run the tests using the github URL when not i sandboxed to simplify the process of running tests locally.

**Comment by zshipko** [comment]
I'm not using `irmin-test` here because the GraphQL client does not conform to `Irmin.S` like the HTTP client does.

Should I work on getting `Irmin_graphql.Client.S` to match `Irmin.S`?

**Comment by samoht** [comment]
Ha yes I see. I think it would be helpful to have `irmin-graphl` client satisfies `Irmin.S` so you could switch the client implementation transparently (at least when using OCaml); also it would help to replace the `irmin-http` client which currently only use the private API calls (and so every high-level function call generates a lot of low-level RPC roundtrip). That would show the benefit of using GraphQL here.

**Comment by zshipko** [comment]
No problem, I will spend some time working on getting `Irmin_graphql.Client.S` to conform to `Irmin.S` - should hopefully have something by early next week.

**Pull request closed without merging**
