### PR TITLE
irmin-pack: remove pack locks

### PR DESCRIPTION
**Pull request by samoht**
This doesn't seem to be necessary.

### CODE REVIEW

**Comment by samoht** [comment]
So it seems that these locks were not very useful 😅 I am not sure how to test this more thoroughly but the benchmarks and the tests continue to pass without these.

**Comment by pascutto** [comment]
Sounds reasonable. Will give it another round of tests inside a Tezos node.

**Comment by samoht** [comment]
Any bootstrap results to share?

**Review by pascutto — APPROVED** [review]
I ran a node for a few hours, and didn't see anything unusual there when it comes to locks.
I don't know about the `pause`s though, but I understood they were there to orchestrate the layered stores? /cc @icristescu

**Review by CraigFe — APPROVED** [review]

**Comment by CraigFe** [comment]
Rebased; ready to go.

**Pull request merged**
