### PR TITLE
Add V1.{export,import} functions

### PR DESCRIPTION
**Pull request by samoht**
/cc @zshipko I think it would be great to include this in the 2.0 release to ease the manipulation of V1 values.

### CODE REVIEW

**Comment by zshipko** [comment]
This also looks good to merge before the release!

**Comment by samoht** [comment]
Rebased

**Comment by samoht** [comment]
A new error!

```
#=== ERROR while compiling git-http.2.0.0 =====================================#
# context     2.0.3 | linux/x86_64 | ocaml-base-compiler.4.05.0 | git://github.com/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.05.0/.opam-switch/build/git-http.2.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p git-http -j 1
# exit-code   1
# env-file    ~/.opam/log/git-http-5542-6f6e69.env
# output-file ~/.opam/log/git-http-5542-6f6e69.out
### output ###
# File "src/git-http/dune", line 4, characters 33-40:
# 4 |  (libraries   git cohttp-lwt uri sexplib))
#                                      ^^^^^^^
# Error: Library "sexplib" not found.
# Hint: try: dune external-lib-deps --missing -j 1 -p git-http @@default
```

Probably best to just remove sexplib in `git-http` if we can /cc @dinosaure

**Comment by samoht** [comment]
I've restarted the CI

**Pull request merged**
