### PR TITLE
CI: use more recent version of the compiler to test mirage packages

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by avsm** [comment]
why not just test all packages on all versions? we can set proper constraints then. (move DEPOPTS to the global env)

**Comment by samoht** [comment]
```
[ERROR] No solution for irmin-mirage-git: The following dependencies couldn't be met:
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> conduit-lwt >= 1.4.0 -> conduit >= 1.4.0 -> ipaddr < 4.0.0 -> ppx_sexp_conv < v0.11 -> ocaml < 4.03
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> conduit-lwt >= 1.4.0 -> conduit >= 1.4.0 -> ipaddr < 4.0.0 -> ppx_sexp_conv < v0.11 -> ppx_core < v0.11 -> ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> conduit-lwt >= 1.4.0 -> conduit >= 1.4.0 -> ipaddr < 4.0.0 -> ppx_sexp_conv < v0.11 -> ppx_core < v0.11 -> base < v0.11 -> ocaml < 4.07.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> conduit-lwt >= 1.4.0 -> conduit >= 1.4.0 -> ipaddr < 4.0.0 -> ppx_sexp_conv < v0.11 -> sexplib < 113.25.00 -> ocaml < 4.03.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> conduit-lwt >= 1.4.0 -> conduit >= 1.4.0 -> ipaddr < 4.0.0 -> ocaml < 4.04.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> ipaddr < 3.0.0 -> ppx_sexp_conv < v0.11 -> ocaml < 4.03
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> ipaddr < 3.0.0 -> ppx_sexp_conv < v0.11 -> ppx_core < v0.11 -> ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> ipaddr < 3.0.0 -> ppx_sexp_conv < v0.11 -> ppx_core < v0.11 -> base < v0.11 -> ocaml < 4.07.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> ipaddr < 3.0.0 -> ppx_sexp_conv < v0.11 -> sexplib < 113.25.00 -> ocaml < 4.03.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> ipaddr < 3.0.0 -> ocaml < 4.04.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> mirage-dns >= 3.0.0 -> mirage-kv-lwt < 2.0.0
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> mirage-conduit >= 3.0.0 -> mirage-dns >= 3.0.0 -> dns-lwt >= 1.1.2 -> dns >= 1.1.3 -> ipaddr >= 4.0.0
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> git < 2.0.0 -> dolog < 1.0 -> ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> git-mirage >= 1.11.4 -> git < 2.0.0 -> ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - irmin-mirage-git -> irmin-git >= 1.3.0 -> git >= 2.1.0
          - irmin-mirage-git -> mirage-kv-lwt >= 2.0.0
        Your request can't be satisfied:
          - No available version of git satisfies the constraints
          - No available version of ipaddr satisfies the constraints
          - No available version of mirage-kv-lwt satisfies the constraints
```

**Comment by samoht** [comment]
> why not just test all packages on all versions? we can set proper constraints then. (move DEPOPTS to the global env)

I just want to be sure that the tests of every package is really run. Maybe there's a better way to do this, but I think the CI scripts are just testing the one set with `PACKAGE`.

**Comment by avsm** [comment]
we should have one test with a dry run for installability, perhaps

**Pull request merged**
