### PR TITLE
Add integrity-check-index command to irmin_fsck

### PR DESCRIPTION
**Pull request by icristescu**
- check a corrupted store
```
time PACK=tezos dune exec -- ./test/irmin-pack/cli/irmin_fsck.exe integrity-check-index ../store/pirbo-tezos-node_20210521/context/
>> Beginning index checking with parameters: { log_size = 500000 }
Reconstructing index     4.8 GiB  09:42  [###############################.]  97%irmin-fsck: internal error, uncaught exception:
            (Failure
              "Pack entry with idx=49_972_463 containing [5254590022,358,\"N\"] is bound to [5313859794,358,\"N\"] in index")
________________________________________________________
Executed in  522.20 secs
```
- reconstruct index 
```
time PACK=tezos dune exec -- ./test/irmin-pack/cli/irmin_fsck.exe reconstruct-index --index-log-size=10_000_000 ../store/pirbo-tezos-node_20210521/context/
>> Beginning index reconstruction with parameters: { log_size = 10000000 }
Reconstructing index   622.4 MiB  01:50  [###.............................]  12%Semaphore replace was blocked for 1.145s
Reconstructing index     2.6 GiB  02:17  [################................]  53%Semaphore merge { id=3 } was blocked for 21.293s
Reconstructing index     3.7 GiB  04:34  [########################........]  75%Semaphore merge { id=4 } was blocked for 21.235s
Reconstructing index     4.8 GiB  05:47  [###############################.]  97%Semaphore merge { id=5 } was blocked for 23.914s
Reconstructing index     5.0 GiB  05:25  [################################] 100%
>> Completed indexing of pack entries. Running a final merge ...
Semaphore merge { id=6 } was blocked for 14.723s
Semaphore close was blocked for 8.965s
>> Success in 5min48s. Store statistics:
  { "Contents" = 6952062;
    "Commit" = 30419;
    "Node" = 38251454;
    "Inode" = 5739746 }

________________________________________________________
Executed in  349.76 secs
```
- but then when rechecking the now repaired store, I still have the same error:
```
time PACK=tezos dune exec -- ./test/irmin-pack/cli/irmin_fsck.exe integrity-check-index ../store/pirbo-tezos-node_20210521/context/
>> Beginning index checking with parameters: { log_size = 500000 }
Reconstructing index     4.8 GiB  04:50  [###############################.]  97%irmin-fsck: internal error, uncaught exception:
            (Failure
              "Pack entry with idx=49_972_463 containing [5254590022,358,\"N\"] is bound to [5313859794,358,\"N\"] in index")


________________________________________________________
Executed in  233.98 secs
```

The duplicate entries from the pack file are added to the index twice and so they are still problematic as long as they are in the pack?

(draft for now because I'm not sure I can get irmin_fsck to compile with the dependence for tezos-context-hash. But it is easier to test the `reconstruct-index` and `integrity-check-index` directly from irmin.)

### CODE REVIEW

**Comment by Ngoguey42** [comment]
> The duplicate entries from the pack file are added to the index twice and so they are still problematic as long as they are in the pack?

The index function is used being `replace`, I don't think that this is a problem.

https://github.com/mirage/irmin/blob/master/src/irmin-pack/pack_index.ml#L60

**Comment by samoht** [comment]
Duplicate entries in the pack files are not an issue (it's a waste of space, but sometimes it's good to do this to improve page locality). `check` should not fail for this. We can maybe report some stats about these if we really want to do something about it :-)

**Comment by icristescu** [comment]
The check only fails on missing hashes now
```
time PACK=tezos dune exec -- ./test/irmin-pack/cli/irmin_fsck.exe integrity-check-index ../store/pirbo-tezos-node_20210521/context/
>> Beginning index checking with parameters: { log_size = 500000 }
Reconstructing index     4.9 GiB  13:32  [###############################.]  98%irmin-fsck: internal error, uncaught exception:
            (Failure
              "Pack entry with idx=50_472_176 containing [5313687344,110,\"B\"] is not bound in index")


________________________________________________________
Executed in  752.63 secs
```
and it does not fail anymore on the reconstructed index, but reports the number of entries in pack that are different from index 
```
>> Success in 6min27s. Store statistics:
  { "Contents" = 6952062;
    "Commit" = 30419;
    "Node" = 38251454;
    "Inode" = 5739746;
    "Inconsistent entries" = 499713 }
```
and `499713` is indeed the number of duplicate hashes in pack.

**Comment by samoht** [comment]
Great! Last requst, could you make the output a bit less "scary" to the end-users :-) e.g with proper formatting, not showing "internal error, uncaught exception", etc.

**Comment by icristescu** [comment]
the new output
```
PACK=tezos dune exec -- ./test/irmin-pack/cli/irmin_fsck.exe integrity-check-index ../store/pirbo-tezos-node_20210521/context/
>> Beginning index checking with parameters: { log_size = 500000 }
Checking index     5.0 GiB  04:50  [######################################] 100%
>> Completed checking of pack entries.
Detected missing hashes in 3min50s. Pack entry {"idx_pack":49972463,"binding":{"key":"CoW8oMZs7soaKMuMDgPsvJfHBdDKrpXV4gm3UP1vWM7RwnU5GuQY","data":[5313717175,358,"N"]}} is not bound in index. 
Store statistics:
  { "Contents" = 6952062;
    "Commit" = 30419;
    "Node" = 38251454;
    "Inode" = 5739746;
    "Inconsistent entries" = 499713;
    "Missing entries" = 288 }
```
as a side, the time for reconstruct and check index vary a lot (between 4min and 19min).

**Comment by samoht** [comment]
Almost perfect :-) just make sure it fits in 80 columns (e.g. a a few newlines) so that it fits on a "normal" console window. Check how `git fsck` do it for instance:

```shell
$ git fsck
Checking object directories: 100% (256/256), done.
Checking object directories: 100% (256/256), done.
Checking objects: 100% (217021/217021), done.
dangling commit c35031782211524e39dd49a5f6dd4dfed6e90593
dangling commit aa8b812a373344642c3694d6ccd5475ea724c6b4
dangling commit 6845bd77f82739333d893c07ca7e973908facb05
```

**Comment by samoht** [comment]
Also rename `"Inconsistent entries" = 499713` into something a bit less scary :-) maybe just "duplicate entries"?

**Comment by icristescu** [comment]
is this better?
```
PACK=tezos dune exec -- ./test/irmin-pack/cli/irmin_fsck.exe integrity-check-index ../store/pirbo-tezos-node_20210521/context/
>> Beginning index checking with parameters: { log_size = 500000 }
Checking index     5.0 GiB  05:58  [######################################] 100%
Detected missing entries in 4min58s.
First pack entry missing from index
   { "entry in pack" = 49972463;
     "index binding" =
      { "key" = CoW8oMZs7soaKMuMDgPsvJfHBdDKrpXV4gm3UP1vWM7RwnU5GuQY;
        "data" = [5313717175,358,"N"] } }
Store statistics:
  { "Contents" = 6952062;
    "Commit" = 30419;
    "Node" = 38251454;
    "Inode" = 5739746;
    "Duplicated entries" = 499713;
    "Missing entries" = 288 }
```

@CraigFe to make the irmin-fsck compile with the tezos binding, I removed the package stanza from the [cli/dune](https://github.com/mirage/irmin/pull/1480/commits/925b83691a7f947f9a5ea74b6e2d96dce60fd179#diff-3e123f1ce96149d483fe9a1d255c0149f3efe1f12dfa1e5f364248b1c505930b). I'm not sure if this is the right way to go.

**Comment by samoht** [comment]
I'm not super convinced by mixing text (for human) and JSON (for machine) outputs, but that can be improved later on.

I am not sure to understand how you get the `data` part of the output, as that hash is supposed to be missing in the index file? Are you somehow inferring it?

**Comment by CraigFe** [comment]
> @CraigFe to make the irmin-fsck compile with the tezos binding, I removed the package stanza from the cli/dune

@icristescu: this means that users who do `opam install irmin-pack` don't have access to this binary, but it isn't much use to them w/o Tezos compatibility anyway. I'll try to find a solution that offers both at some point (and doesn't break `opam-ci`...).

**Comment by icristescu** [comment]
Replaced the json output with 
```
First pack entry missing from index is the 49972463 entry of the pack:
  Node with hash CoW8oMZs7soaKMuMDgPsvJfHBdDKrpXV4gm3UP1vWM7RwnU5GuQY
  pack offset = 5313717175, length = 358
```
I think the offset is maybe interesting for debugging, but I can remove the length and/or offset. 

The "data" in the previous output is indeed inferred from the pack file (its the index value consisting of the offset, the length and the kind).

**Comment by samoht** [comment]
> The "data" in the previous output is indeed inferred from the pack file (its the index value consisting of the offset, the length and the kind).

Interesting, so we could speed-up the reconstruct command by just adding the missing hashes at the end :-) (instead of starting from scratch)

Othewise, the new output looks great. Thanks for your patience! :-)

**Review by samoht — APPROVED** [review]

**Comment by icristescu** [comment]
> Interesting, so we could speed-up the reconstruct command by just adding the missing hashes at the end :-) (instead of starting from scratch)

Yes, indeed!

> Othewise, the new output looks great. Thanks for your patience! :-)

Thank you, it does look better now :)

**Comment by icristescu** [comment]
Planning to merge this, this morning.

**Review by Ngoguey42 — APPROVED** [review]

**Pull request merged**
