### PR TITLE
irmin-pack: add GC design docs

### PR DESCRIPTION
**Pull request by metanivek**
This PR adds design docs for different phases of GC work.

### CODE REVIEW

**Comment by adatario** [comment]
Nit: Can you add the figures to the repo? It would be nice if the documentation is self-contained and does not rely on external resources from imgur.

**Comment by samoht** [comment]
Another nit: probably best not to add a pdf file to the repo.

**Comment by metanivek** [comment]
@adatario yeah, I agree. I was mostly just being lazy but will take care of it. :sweat_smile: (/me grumbles about hackmd not having a good export...)

@samoht this pdf was copied from https://github.com/tomjridge/public_notes/blob/master/2022-02-03_layered_store_design.pdf. I like not relying on another source, but if we don't want it in the repo I could just link to it (unless somebody feels excited to re-do the doc in a text-based format!).

**Comment by samoht** [comment]
I've pushed a markdownified version of the layered store design.

**Comment by metanivek** [comment]
Thanks @samoht! I'll update my commit next week to remove the pdf and add the images.

**Comment by metanivek** [comment]
All updated with in-repo images now @adatario @samoht!

For reference, I used this little script to automate the extraction/replacement of the images. It could be useful for future additions/updates if they originate in hackmd. I could add it to the repo, add it to the readme, or just leave it as a comment here. Any opinions?

```sh
#!/usr/bin/env sh
set -e

FILE=$(basename "$1")
LOC=$(basename "$FILE" .md)
DIR="imgs/$LOC"

echo "Make dir $DIR"
mkdir -p "$DIR"

echo "Download images from $FILE"
grep -oP "https://.*imgur.*png" "$FILE" | xargs wget -P "$DIR"

echo "Replace links in $FILE"
sed -i "s,https://i\.imgur\.com,./$DIR,g" "$FILE"

echo "Done"
```

**Review by samoht — APPROVED** [review]

**Pull request merged**
