### PR TITLE
Upgrade to OCamlformat v0.14.0

### PR DESCRIPTION
**Pull request by CraigFe**
- reformats the code to be compliant with OCamlformat v0.14.0
- updates the `.ocamlformat` file accordingly

### CODE REVIEW

**Comment by hannesm** [comment]
I looked through the diff, and through the release notes of ocamlformat (https://github.com/ocaml-ppx/ocamlformat/releases/tag/0.14.0), and still don't have a clue why the documentation comments are now before the `type` keyword instead of after it. Is this the general rule: documentation comments before `type`, and after `val`?

**Comment by samoht** [comment]
The goal is to simplify the heuristic of comment attachement (see https://discuss.ocaml.org/t/ann-ocamlformat-0-14-0/5435). I am not thrilled by that change but I welcome any simplification/consistency there.

**Comment by hannesm** [comment]
thanks for explanation and link @samoht - this makes sense. not to self: read discourse instead of changes

**Comment by samoht** [comment]
@CraigFe please wait a bit before merging this.

**Comment by CraigFe** [comment]
> @CraigFe please wait a bit before merging this.

Merge when ready :slightly_smiling_face: I want to wait for `ocaml-ci` to notice OCamlformat 0.14.0 at the very least, which won't happen for another week or two.

**Comment by pascutto** [comment]
The CI seems ready for it, are we? @samoht

**Comment by samoht** [comment]
I am still a bit unsure about that change. Can you try to put all comments before and see how it looks like so at least we have a bit of consistency?

**Comment by CraigFe** [comment]
I've added a commit that sets `doc-comments-val=before`. This increases the diff size from ~200 lines to ~800 lines.

Personally, I prefer `doc-comments-val=after` to be consistent with Odoc's rendering of them, but since this is no longer true in the `type` case perhaps that's a lost cause :shrug:

**Comment by samoht** [comment]
> Personally, I prefer doc-comments-val=after to be consistent with Odoc's rendering of them, but since this is no longer true in the type case perhaps that's a lost cause 🤷

Yes that's why I am hesitant to change this right now.

**Comment by CraigFe** [comment]
Closing this now (and my other automated ones on `mirage/`). I'll make a follow-up PR once the situation around comment placement is a bit clearer.

**Comment by samoht** [comment]
The 0.14.1 release (released yesterday) should reduces the diff.

**Comment by pascutto** [comment]
If I understood correctly, the last release (`0.14.1`) fixes the issue.

**Pull request closed without merging**
