### PR TITLE
Pass cancel to copy_newies_to_next_upper

### PR DESCRIPTION
**Pull request by Ngoguey42**
Since `copy_newies` supports `cancel` but the parameter is never passed it, I guess it's an oversight.

### CODE REVIEW

**Review by icristescu — APPROVED** [review]
Good catch! it would be nice to cover this case in the tests for cancel

**Comment by Ngoguey42** [comment]
> Good catch! it would be nice to cover this case in the tests for cancel

Indeed, but complicated. 

Testing `cancel_existing` in general is going to necessitate some slight modifications of the source code, like adding more hooks. I open a ticket about it.

**Comment by CraigFe** [comment]
Since these functions have very few call-sites, I think it's best to make the `cancel` argument non-optional and force `~cancel:None` in the appropriate places.

This also needs rebased over my layered stores extraction – sorry about that.

**Review by CraigFe — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
