### PR TITLE
Support Irmin.Generic_key.S in irmin-graphql

### PR DESCRIPTION
**Pull request by zshipko**
Since irmin-graphql isn’t very well tested, it would probably be worthwhile to include some additional tests before considering this PR ready.

### CODE REVIEW

**Comment by zshipko** [comment]
I added a test for `commit_key` and think this is getting pretty close. The only thing left is to expose `kinded_key` on trees.

**Comment by zshipko** [comment]
Unfortunately the representation we use for `tree` expects an associated `path` which means that `Tree.of_key` won't work without rewriting the `Tree` and `Contents` schema types to make that path optional, which I think is outside the scope of this PR. I was able to get `Tree.to_key` and `Contents.of_key` working though.

**Comment by zshipko** [comment]
I think this is ready for a review - the tests are still pretty sparse but I plan to make another PR to improve the `irmin-graphql` test suite.

**Review by CraigFe — APPROVED** [review]
LGTM, thanks! Can you extend the changelog entry to be more descriptive of the API changes involved? (e.g. "key" is now "path")

**Pull request merged**
