### PR TITLE
Distinguish between empty trees and non-existent sub-trees

### PR DESCRIPTION
**Pull request by samoht**
Change `S.find_tree` to return an optional value. This allows to not conflate
the meaning of `Empty: it is now only "an empty subtree". And we use None to
denote non-existent sub-trees.

### CODE REVIEW

**Comment by talex5** [comment]
Why is `Empty` not just `Node Node.empty`?

**Comment by samoht** [comment]
Because this you can create a tree (starting from an empty tree) without having to tie it to a store.

**Comment by samoht** [comment]
(e.g. `Node.empty` is the hash of the empty tree, so need to be stored in the store first)

**Comment by talex5** [comment]
Where is this? `ir_node.ml` defines:

    let empty = of_list []

Seems like any other implementation of `NODE` must define an `empty` too. Maybe internally they distinguish between a hash and empty, but why expose it in the `tree` type?

**Comment by samoht** [comment]
I've pushed a commit to remove `Empty`, it's a bit more complex that I would like as it forces `Tree.empty` to become a function: it's because the all node values have an associated (lazy) hash, and this could be cached if you save the empty value once, delete your DB on disk and use the empty value again. Then you will have a "not found" when trying to look for that hash.

I think ideally we would cache the empty value in the `Repo.t` value, but currently it is a bit hard to do.

**Comment by talex5** [comment]
Ah, because when you save a `tree` the empty node changes from a map to a hash?

But couldn't `export_map` always export the empty map as `P.Node.Val.empty` to avoid that?

**Comment by samoht** [comment]
Reverted and fixed in https://github.com/mirage/irmin/pull/435

**Pull request merged**
