### PR TITLE
irmin-fdb: FoundationDB store

### PR DESCRIPTION
**Pull request by andreas**
This PR is work-in-progress -- beware of force pushes. It implements an Irmin store backed by [FoundationDB](https://foundationdb.org) using [`ocaml-fdb`](https://github.com/andreas/ocaml-fdb).

### CODE REVIEW

**Comment by andreas** [comment]
The Irmin store tests now pass locally on my machine 🎉 

@samoht, a couple of questions...

- **Value length limit**

  Values in FoundationDB cannot exceed 100,000 bytes in size. I ran into this issue when running the Irmin store tests. I've fixed it by using `Irmin_chunk`. Does this seem like a reasonable approach?

- **Watches**

  Irmin watches can either be based on `Irmin.Private.Watch`, in which case running two `irmin-fdb` processes backed by the same FDB instance will not trigger watches correctly between them, since they are just kept in-memory.

  Alternatively Irmin watches can be based on FDB watches, which will work across multiple `irmin-fdb` instances, but does not allow for an easy way to watch *all* keys (it's possible, but tricky).

  What do you think is best?

- **Packaging and CI**

  I assume `irmin-fdb` should be part of the `irmin` repo? Running `irmin-fdb` tests will require installing `libfdb` on Travis. Any concerns in that regard?

**Comment by samoht** [comment]
That's great !!!

- * Value length limit*:  yes, you can use irmin-chunk for this. This has a small overhead but that should be fine in most cases -- we can make sure later (when irmin-bench is ready) that the overhead is indeed minimal.

- * Watches*: it really depends on the use-case, but I guess for fdb it would be great to use the store in a distributed fashion, when not all worker share the same address space -- and for this we need FDB watches. As far as I know you don't need to watch all keys: just the ones corresponding to branch names (e.g. the ones in the "Atomic write stores" part). The immutable entries doesn't need to be watched.

- ** Packaging and CI* yes, you could add you package in that repo if you agree to help maintaining it :-) No pb to install it on the CI if it's available. Does fddb work only on MacOS ?

**Comment by andreas** [comment]
> * *Watches*: it really depends on the use-case, but I guess for fdb it would be great to use the store in a distributed fashion, when not all worker share the same address space -- and for this we need FDB watches. As far as I know you don't need to watch all keys: just the ones corresponding to branch names (e.g. the ones in the "Atomic write stores" part). The immutable entries doesn't need to be watched.

Specifically, my concern is [`ATOMIC_WRITE_STORE.watch`](https://github.com/mirage/irmin/blob/9c070e4f1c5eac9c01ef0c9acd5874ed5ee3875f/src/irmin/irmin.mli#L910-L916) vs [`ATOMIC_WRITE_STORE.watch_key`](https://github.com/mirage/irmin/blob/9c070e4f1c5eac9c01ef0c9acd5874ed5ee3875f/src/irmin/irmin.mli#L918-L923). Watching a single key (`watch_key`) can be done efficiently with FDB watches, while watching the entire store (`watch`) is much more tricky (though not impossible). Essentially FDB only allows watching a single key, so we would have to come up with some scheme based on that.

I'll start out with implementing `watch_key` and leaving out `watch`..

> * *Packaging and CI* yes, you could add you package in that repo if you agree to help maintaining it :-) No pb to install it on the CI if it's available. Does fddb work only on MacOS ?

Great. `libfdb` works on Linux, MacOS and Windows, so no problem there. I was just concerned about complicating the Travis config for all Irmin packages.

**Comment by andreas** [comment]
Thinking more about this, leaving out `watch` sucks as the Irmin store tests will fail and it's a nice capability to provide anyway. As such, I started looking more into implementing `watch` based on FDB watches.

Consider the following following scheme for implementing `watch` based on FDB watches: When the user requests watching all keys, an FDB watch is created for a magic key, `watch-all-magic-key`. Every time the atomic store is modified, the magic key is incremented atomically. This will trigger the FDB watch, which then has to determine which specific keys have been modified, e.g. by iterating over all keys. If this key set is small, then this scheme is reasonable, but otherwise not.

What assumptions, if any, can I make about the number of entities being watched? Based on this comment, I would think it's only branches, not keys:

> As far as I know you don't need to watch all keys: just the ones corresponding to branch names (e.g. the ones in the "Atomic write stores" part). The immutable entries doesn't need to be watched.

Looking over the code and playing around with `irmin-graphql`, it appears the user can actually watch all keys. I would assume that `number branches << number keys`, so this leads to different design constraints. Can you help clarify this, @samoht?

While reading the existing implementation of watches, I noticed there's a map from keys to values that is kept in-memory ([source](https://github.com/mirage/irmin/blob/f0cfeb8265d657f3f6aa70ae324225372839a253/src/irmin/watch.ml#L111)). This approach should suffer from some of the same problems (keeping a large key/value set in memory), so I'm a bit puzzled 🤔

**Comment by andreas** [comment]
I've moved this to [andreas/irmin-fdb](https://github.com/andreas/irmin-fdb) for now, as it's easier to fiddle with CI and other work-in-progress things.

**Pull request closed without merging**
